// Code generated by unobin. DO NOT EDIT.
package main

import (
	lib_aws "github.com/cloudboss/unobin-library-aws"
	"github.com/cloudboss/unobin/pkg/runner"
	"github.com/cloudboss/unobin/pkg/runtime"
)

const (
	factoryBody        = "factory: {\n  imports: { aws: 'github.com/cloudboss/unobin-library-aws' }\n}\n"
	factoryLibraryPath = ""
	factoryName        = "demo-factory"
)

// Stamped at link time via -ldflags.
var (
	factoryVersion  string
	contentRevision string
	unobinVersion   string
)

func main() {
	runner.Run(runner.Info{
		FactoryName:     factoryName,
		FactoryVersion:  factoryVersion,
		ContentRevision: contentRevision,
		FactoryBody:     factoryBody,
		LibraryPath:     factoryLibraryPath,
		Libraries: map[string]*runtime.Library{
			"aws": runtime.LibraryWithPath(
				lib_aws.Library(),
				"github.com/cloudboss/unobin-library-aws",
			),
		},
		UnobinVersion: unobinVersion,
	})
}
