// Code generated by unobin. DO NOT EDIT.
package main

import (
	lib_a "demo-factory/internal/a"
	lib_wrap "demo-factory/internal/wrap"
	"github.com/cloudboss/unobin/pkg/runner"
	"github.com/cloudboss/unobin/pkg/runtime"
)

const (
	factoryBody        = "factory: {\n  imports: {\n    a:    './a'\n    wrap: './wrap'\n  }\n\n  data-sources: {\n    root: a.first {}\n    nested: wrap.box {}\n  }\n}\n"
	factoryLibraryPath = ""
	factoryName        = "demo-factory"
)

// Stamped at link time via -ldflags.
var (
	factoryVersion  string
	contentRevision string
	unobinVersion   string
)

func main() {
	runner.Run(runner.Info{
		FactoryName:     factoryName,
		FactoryVersion:  factoryVersion,
		ContentRevision: contentRevision,
		FactoryBody:     factoryBody,
		LibraryPath:     factoryLibraryPath,
		Libraries: map[string]*runtime.Library{
			"a": runtime.LibraryWithPath(
				lib_a.Library(),
				"demo-factory/internal/a",
			),
			"wrap": runtime.LibraryWithPath(
				lib_wrap.Library(),
				"demo-factory/internal/wrap",
			),
		},
		UnobinVersion: unobinVersion,
	})
}
