// Code generated by unobin. DO NOT EDIT.
package wrap

import (
	lib_a_a6595328 "demo-factory/internal/a_a6595328"
	"github.com/cloudboss/unobin/pkg/lang"
	"github.com/cloudboss/unobin/pkg/lang/syntax"
	"github.com/cloudboss/unobin/pkg/runtime"
)

func Library() *runtime.Library {
	return &runtime.Library{
		Name: "wrap",
		DataComposites: map[string]*runtime.CompositeType{
			"box": {
				Name:       "box",
				Kind:       runtime.NodeDataSource,
				SyntaxBody: &syntax.FactoryBody{Imports: []syntax.ImportDecl{{Alias: syntax.Ident{Name: "a"}, Ref: &lang.StringLit{Value: "../b"}}}, Data: []syntax.NodeDecl{{Kind: syntax.NodeKind("data-source"), Name: syntax.Ident{Name: "inner"}, Selector: syntax.NodeSelector{Alias: syntax.Ident{Name: "a"}, Export: syntax.Ident{Name: "second"}}, Body: &lang.ObjectLit{Fields: []*lang.Field{}}}}, Outputs: []syntax.OutputDecl{{Name: syntax.Ident{Name: "value"}, Body: &lang.ObjectLit{Fields: []*lang.Field{{Key: lang.FieldKey{Kind: lang.FieldIdent, Name: "value"}, Value: &lang.DotPath{Root: &lang.Ident{Name: "data-source"}, Segments: []lang.DotSegment{{Name: "inner"}, {Name: "value"}}}}}}}}},
				Libraries: map[string]*runtime.Library{
					"a": runtime.LibraryWithPath(
						lib_a_a6595328.Library(),
						"demo-factory/internal/a_a6595328",
					),
				},
			},
		},
	}
}
