// Code generated by unobin. DO NOT EDIT.
package main

import (
	"github.com/cloudboss/unobin/pkg/runner"
	"github.com/cloudboss/unobin/pkg/runtime"
	lib_core "github.com/x/core/lib"
)

const (
	factoryBody        = "factory: {\n  imports: { core: 'github.com/x/core//lib' }\n}\n"
	factoryLibraryPath = ""
	factoryName        = "demo-factory"
)

// Stamped at link time via -ldflags.
var (
	factoryVersion  string
	contentRevision string
	unobinVersion   string
)

func main() {
	runner.Run(runner.Info{
		FactoryName:     factoryName,
		FactoryVersion:  factoryVersion,
		ContentRevision: contentRevision,
		FactoryBody:     factoryBody,
		LibraryPath:     factoryLibraryPath,
		Libraries: map[string]*runtime.Library{
			"core": runtime.LibraryWithPath(
				lib_core.Library(),
				"github.com/x/core/lib",
			),
		},
		UnobinVersion: unobinVersion,
	})
}
