ARG FROM
FROM ${FROM}

ARG USER_ID
ARG GROUP_ID

RUN apt-get update \
    && apt-get install -y --no-install-recommends nodejs npm python3 \
    && rm -rf /var/lib/apt/lists/*

RUN if ! getent group "${GROUP_ID}" >/dev/null; then \
        groupadd --gid "${GROUP_ID}" builder; \
    fi \
    && if ! getent passwd "${USER_ID}" >/dev/null; then \
        useradd --uid "${USER_ID}" --gid "${GROUP_ID}" --create-home builder; \
    fi

USER ${USER_ID}:${GROUP_ID}
