// Code generated by pigeon; DO NOT EDIT.

package parse

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"math"
	"os"
	"sort"
	"strconv"
	"strings"
	"sync"
	"unicode"
	"unicode/utf8"
)

// span returns a Span whose Start is the parser's current position. End is
// left zero; that is intentional until expressions land and a use case for
// end-of-match position appears.
func (c *current) span() Span {
	pos := Position{
		Line:   c.pos.line,
		Column: c.pos.col,
		Offset: c.pos.offset,
	}
	if f, ok := c.globalStore["file"].(string); ok {
		pos.File = f
	}
	return Span{Start: pos}
}

// processMultiline turns a backtick delimited literal into its decoded
// value. text includes the surrounding backticks; startCol is the column
// of the opening backtick. Single line forms (no newline in the body)
// are returned verbatim. Multiline forms drop the first newline after
// the opening backtick and strip the closing backtick column's indent
// prefix from every content line. Lines with less indentation are a
// parse error.
func processMultiline(text []byte, startCol int) (string, error) {
	if len(text) < 2 {
		return "", fmt.Errorf("multiline string too short")
	}
	body := text[1 : len(text)-1]
	if !bytes.ContainsAny(body, "\n\r") {
		return string(body), nil
	}
	switch {
	case body[0] == '\n':
		body = body[1:]
	case len(body) >= 2 && body[0] == '\r' && body[1] == '\n':
		body = body[2:]
	}
	col := startCol
	for i := 0; i < len(text)-1; i++ {
		switch text[i] {
		case '\n':
			col = 1
		case '\r':
		default:
			col++
		}
	}
	closeCol := col
	if closeCol <= 1 {
		return string(body), nil
	}
	stripN := closeCol - 1
	lines := strings.Split(string(body), "\n")
	out := make([]string, 0, len(lines))
	for i, ln := range lines {
		ln = strings.TrimRight(ln, "\r")
		if i == len(lines)-1 {
			if strings.TrimSpace(ln) != "" {
				return "", fmt.Errorf("multiline string: closing backtick has content on its line")
			}
			continue
		}
		if len(ln) < stripN {
			if strings.TrimSpace(ln) == "" {
				out = append(out, "")
				continue
			}
			return "", fmt.Errorf("multiline string: line has less indentation than the closing backtick")
		}
		if strings.TrimSpace(ln[:stripN]) != "" {
			return "", fmt.Errorf("multiline string: line does not start with the closing backtick indent")
		}
		out = append(out, ln[stripN:])
	}
	if len(out) == 0 {
		return "", nil
	}
	return strings.Join(out, "\n") + "\n", nil
}

// fieldSlice converts pigeon's []any of pair captures to []*Field.
func fieldSlice(v any) []*Field {
	if v == nil {
		return nil
	}
	in := v.([]any)
	if len(in) == 0 {
		return nil
	}
	out := make([]*Field, len(in))
	for i, x := range in {
		out[i] = x.(*Field)
	}
	return out
}

// exprSlice converts pigeon's []any of element captures to []Expr.
func exprSlice(v any) []Expr {
	if v == nil {
		return nil
	}
	in := v.([]any)
	if len(in) == 0 {
		return nil
	}
	out := make([]Expr, len(in))
	for i, x := range in {
		out[i] = x.(Expr)
	}
	return out
}

// infixTail carries one (op, right) tail produced by an operator-level
// rule. The leftmost operand is the head; foldInfix combines a head with
// any number of tails into a left-associated Infix tree.
type infixTail struct {
	op    string
	right Expr
}

func foldInfix(left Expr, rest any) Expr {
	if rest == nil {
		return left
	}
	cur := left
	for _, t := range rest.([]any) {
		tail := t.(infixTail)
		cur = &Infix{S: cur.Span(), Op: tail.op, Left: cur, Right: tail.right}
	}
	return cur
}

func dotSegments(v any) []DotSegment {
	in := v.([]any)
	out := make([]DotSegment, len(in))
	for i, x := range in {
		out[i] = x.(DotSegment)
	}
	return out
}

// unquoteSingle decodes a single-quoted string body. Backslash escapes
// recognized: \\ \' \n \t \r \0. An unknown escape is kept literal.
func unquoteSingle(s string) string {
	if !strings.ContainsRune(s, '\\') {
		return s
	}
	var b strings.Builder
	b.Grow(len(s))
	for i := 0; i < len(s); i++ {
		ch := s[i]
		if ch == '\\' && i+1 < len(s) {
			next := s[i+1]
			switch next {
			case '\\':
				b.WriteByte('\\')
			case '\'':
				b.WriteByte('\'')
			case 'n':
				b.WriteByte('\n')
			case 't':
				b.WriteByte('\t')
			case 'r':
				b.WriteByte('\r')
			case '0':
				b.WriteByte(0)
			default:
				b.WriteByte('\\')
				b.WriteByte(next)
			}
			i++
			continue
		}
		b.WriteByte(ch)
	}
	return b.String()
}

var g = &grammar{
	rules: []*rule{
		{
			name: "File",
			pos:  position{line: 192, col: 1, offset: 4370},
			expr: &actionExpr{
				pos: position{line: 192, col: 9, offset: 4378},
				run: (*parser).callonFile1,
				expr: &seqExpr{
					pos: position{line: 192, col: 9, offset: 4378},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 192, col: 9, offset: 4378},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 192, col: 11, offset: 4380},
							label: "pairs",
							expr: &zeroOrMoreExpr{
								pos: position{line: 192, col: 17, offset: 4386},
								expr: &ruleRefExpr{
									pos:  position{line: 192, col: 17, offset: 4386},
									name: "Pair",
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 192, col: 23, offset: 4392},
							name: "EOF",
						},
					},
				},
			},
		},
		{
			name: "Pair",
			pos:  position{line: 203, col: 1, offset: 4744},
			expr: &actionExpr{
				pos: position{line: 203, col: 9, offset: 4752},
				run: (*parser).callonPair1,
				expr: &seqExpr{
					pos: position{line: 203, col: 9, offset: 4752},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 203, col: 9, offset: 4752},
							label: "key",
							expr: &ruleRefExpr{
								pos:  position{line: 203, col: 13, offset: 4756},
								name: "Key",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 203, col: 17, offset: 4760},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 203, col: 19, offset: 4762},
							val:        ":",
							ignoreCase: false,
							want:       "\":\"",
						},
						&ruleRefExpr{
							pos:  position{line: 203, col: 23, offset: 4766},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 203, col: 25, offset: 4768},
							label: "value",
							expr: &ruleRefExpr{
								pos:  position{line: 203, col: 31, offset: 4774},
								name: "Value",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 203, col: 37, offset: 4780},
							name: "_",
						},
						&zeroOrOneExpr{
							pos: position{line: 203, col: 39, offset: 4782},
							expr: &litMatcher{
								pos:        position{line: 203, col: 39, offset: 4782},
								val:        ",",
								ignoreCase: false,
								want:       "\",\"",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 203, col: 44, offset: 4787},
							name: "_",
						},
					},
				},
			},
		},
		{
			name: "Key",
			pos:  position{line: 209, col: 1, offset: 4876},
			expr: &choiceExpr{
				pos: position{line: 209, col: 8, offset: 4883},
				alternatives: []any{
					&ruleRefExpr{
						pos:  position{line: 209, col: 8, offset: 4883},
						name: "IdentKey",
					},
					&ruleRefExpr{
						pos:  position{line: 209, col: 19, offset: 4894},
						name: "StringKey",
					},
				},
			},
		},
		{
			name: "IdentKey",
			pos:  position{line: 211, col: 1, offset: 4905},
			expr: &actionExpr{
				pos: position{line: 211, col: 13, offset: 4917},
				run: (*parser).callonIdentKey1,
				expr: &labeledExpr{
					pos:   position{line: 211, col: 13, offset: 4917},
					label: "name",
					expr: &ruleRefExpr{
						pos:  position{line: 211, col: 18, offset: 4922},
						name: "IdentText",
					},
				},
			},
		},
		{
			name: "StringKey",
			pos:  position{line: 215, col: 1, offset: 5011},
			expr: &actionExpr{
				pos: position{line: 215, col: 14, offset: 5024},
				run: (*parser).callonStringKey1,
				expr: &labeledExpr{
					pos:   position{line: 215, col: 14, offset: 5024},
					label: "s",
					expr: &ruleRefExpr{
						pos:  position{line: 215, col: 16, offset: 5026},
						name: "StringLitNode",
					},
				},
			},
		},
		{
			name: "Value",
			pos:  position{line: 221, col: 1, offset: 5136},
			expr: &ruleRefExpr{
				pos:  position{line: 221, col: 10, offset: 5145},
				name: "Expr",
			},
		},
		{
			name: "Expr",
			pos:  position{line: 223, col: 1, offset: 5151},
			expr: &actionExpr{
				pos: position{line: 223, col: 9, offset: 5159},
				run: (*parser).callonExpr1,
				expr: &seqExpr{
					pos: position{line: 223, col: 9, offset: 5159},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 223, col: 9, offset: 5159},
							label: "left",
							expr: &ruleRefExpr{
								pos:  position{line: 223, col: 14, offset: 5164},
								name: "AndExpr",
							},
						},
						&labeledExpr{
							pos:   position{line: 223, col: 22, offset: 5172},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 223, col: 27, offset: 5177},
								expr: &ruleRefExpr{
									pos:  position{line: 223, col: 27, offset: 5177},
									name: "OrTail",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "OrTail",
			pos:  position{line: 227, col: 1, offset: 5232},
			expr: &actionExpr{
				pos: position{line: 227, col: 11, offset: 5242},
				run: (*parser).callonOrTail1,
				expr: &seqExpr{
					pos: position{line: 227, col: 11, offset: 5242},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 227, col: 11, offset: 5242},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 227, col: 13, offset: 5244},
							val:        "||",
							ignoreCase: false,
							want:       "\"||\"",
						},
						&ruleRefExpr{
							pos:  position{line: 227, col: 18, offset: 5249},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 227, col: 20, offset: 5251},
							label: "right",
							expr: &ruleRefExpr{
								pos:  position{line: 227, col: 26, offset: 5257},
								name: "AndExpr",
							},
						},
					},
				},
			},
		},
		{
			name: "AndExpr",
			pos:  position{line: 231, col: 1, offset: 5324},
			expr: &actionExpr{
				pos: position{line: 231, col: 12, offset: 5335},
				run: (*parser).callonAndExpr1,
				expr: &seqExpr{
					pos: position{line: 231, col: 12, offset: 5335},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 231, col: 12, offset: 5335},
							label: "left",
							expr: &ruleRefExpr{
								pos:  position{line: 231, col: 17, offset: 5340},
								name: "EqualityExpr",
							},
						},
						&labeledExpr{
							pos:   position{line: 231, col: 30, offset: 5353},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 231, col: 35, offset: 5358},
								expr: &ruleRefExpr{
									pos:  position{line: 231, col: 35, offset: 5358},
									name: "AndTail",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "AndTail",
			pos:  position{line: 235, col: 1, offset: 5414},
			expr: &actionExpr{
				pos: position{line: 235, col: 12, offset: 5425},
				run: (*parser).callonAndTail1,
				expr: &seqExpr{
					pos: position{line: 235, col: 12, offset: 5425},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 235, col: 12, offset: 5425},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 235, col: 14, offset: 5427},
							val:        "&&",
							ignoreCase: false,
							want:       "\"&&\"",
						},
						&ruleRefExpr{
							pos:  position{line: 235, col: 19, offset: 5432},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 235, col: 21, offset: 5434},
							label: "right",
							expr: &ruleRefExpr{
								pos:  position{line: 235, col: 27, offset: 5440},
								name: "EqualityExpr",
							},
						},
					},
				},
			},
		},
		{
			name: "EqualityExpr",
			pos:  position{line: 239, col: 1, offset: 5512},
			expr: &actionExpr{
				pos: position{line: 239, col: 17, offset: 5528},
				run: (*parser).callonEqualityExpr1,
				expr: &seqExpr{
					pos: position{line: 239, col: 17, offset: 5528},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 239, col: 17, offset: 5528},
							label: "left",
							expr: &ruleRefExpr{
								pos:  position{line: 239, col: 22, offset: 5533},
								name: "ComparisonExpr",
							},
						},
						&labeledExpr{
							pos:   position{line: 239, col: 37, offset: 5548},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 239, col: 42, offset: 5553},
								expr: &ruleRefExpr{
									pos:  position{line: 239, col: 42, offset: 5553},
									name: "EqualityTail",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "EqualityTail",
			pos:  position{line: 243, col: 1, offset: 5614},
			expr: &actionExpr{
				pos: position{line: 243, col: 17, offset: 5630},
				run: (*parser).callonEqualityTail1,
				expr: &seqExpr{
					pos: position{line: 243, col: 17, offset: 5630},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 243, col: 17, offset: 5630},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 243, col: 19, offset: 5632},
							label: "op",
							expr: &choiceExpr{
								pos: position{line: 243, col: 24, offset: 5637},
								alternatives: []any{
									&litMatcher{
										pos:        position{line: 243, col: 24, offset: 5637},
										val:        "==",
										ignoreCase: false,
										want:       "\"==\"",
									},
									&litMatcher{
										pos:        position{line: 243, col: 31, offset: 5644},
										val:        "!=",
										ignoreCase: false,
										want:       "\"!=\"",
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 243, col: 38, offset: 5651},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 243, col: 40, offset: 5653},
							label: "right",
							expr: &ruleRefExpr{
								pos:  position{line: 243, col: 46, offset: 5659},
								name: "ComparisonExpr",
							},
						},
					},
				},
			},
		},
		{
			name: "ComparisonExpr",
			pos:  position{line: 247, col: 1, offset: 5748},
			expr: &actionExpr{
				pos: position{line: 247, col: 19, offset: 5766},
				run: (*parser).callonComparisonExpr1,
				expr: &seqExpr{
					pos: position{line: 247, col: 19, offset: 5766},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 247, col: 19, offset: 5766},
							label: "left",
							expr: &ruleRefExpr{
								pos:  position{line: 247, col: 24, offset: 5771},
								name: "AdditiveExpr",
							},
						},
						&labeledExpr{
							pos:   position{line: 247, col: 37, offset: 5784},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 247, col: 42, offset: 5789},
								expr: &ruleRefExpr{
									pos:  position{line: 247, col: 42, offset: 5789},
									name: "ComparisonTail",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "ComparisonTail",
			pos:  position{line: 251, col: 1, offset: 5852},
			expr: &actionExpr{
				pos: position{line: 251, col: 19, offset: 5870},
				run: (*parser).callonComparisonTail1,
				expr: &seqExpr{
					pos: position{line: 251, col: 19, offset: 5870},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 251, col: 19, offset: 5870},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 251, col: 21, offset: 5872},
							label: "op",
							expr: &choiceExpr{
								pos: position{line: 251, col: 26, offset: 5877},
								alternatives: []any{
									&litMatcher{
										pos:        position{line: 251, col: 26, offset: 5877},
										val:        "<=",
										ignoreCase: false,
										want:       "\"<=\"",
									},
									&litMatcher{
										pos:        position{line: 251, col: 33, offset: 5884},
										val:        ">=",
										ignoreCase: false,
										want:       "\">=\"",
									},
									&litMatcher{
										pos:        position{line: 251, col: 40, offset: 5891},
										val:        "<",
										ignoreCase: false,
										want:       "\"<\"",
									},
									&litMatcher{
										pos:        position{line: 251, col: 46, offset: 5897},
										val:        ">",
										ignoreCase: false,
										want:       "\">\"",
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 251, col: 52, offset: 5903},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 251, col: 54, offset: 5905},
							label: "right",
							expr: &ruleRefExpr{
								pos:  position{line: 251, col: 60, offset: 5911},
								name: "AdditiveExpr",
							},
						},
					},
				},
			},
		},
		{
			name: "AdditiveExpr",
			pos:  position{line: 255, col: 1, offset: 5998},
			expr: &actionExpr{
				pos: position{line: 255, col: 17, offset: 6014},
				run: (*parser).callonAdditiveExpr1,
				expr: &seqExpr{
					pos: position{line: 255, col: 17, offset: 6014},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 255, col: 17, offset: 6014},
							label: "left",
							expr: &ruleRefExpr{
								pos:  position{line: 255, col: 22, offset: 6019},
								name: "MultiplicativeExpr",
							},
						},
						&labeledExpr{
							pos:   position{line: 255, col: 41, offset: 6038},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 255, col: 46, offset: 6043},
								expr: &ruleRefExpr{
									pos:  position{line: 255, col: 46, offset: 6043},
									name: "AdditiveTail",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "AdditiveTail",
			pos:  position{line: 259, col: 1, offset: 6104},
			expr: &actionExpr{
				pos: position{line: 259, col: 17, offset: 6120},
				run: (*parser).callonAdditiveTail1,
				expr: &seqExpr{
					pos: position{line: 259, col: 17, offset: 6120},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 259, col: 17, offset: 6120},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 259, col: 19, offset: 6122},
							label: "op",
							expr: &choiceExpr{
								pos: position{line: 259, col: 24, offset: 6127},
								alternatives: []any{
									&litMatcher{
										pos:        position{line: 259, col: 24, offset: 6127},
										val:        "+",
										ignoreCase: false,
										want:       "\"+\"",
									},
									&litMatcher{
										pos:        position{line: 259, col: 30, offset: 6133},
										val:        "-",
										ignoreCase: false,
										want:       "\"-\"",
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 259, col: 36, offset: 6139},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 259, col: 38, offset: 6141},
							label: "right",
							expr: &ruleRefExpr{
								pos:  position{line: 259, col: 44, offset: 6147},
								name: "MultiplicativeExpr",
							},
						},
					},
				},
			},
		},
		{
			name: "MultiplicativeExpr",
			pos:  position{line: 263, col: 1, offset: 6240},
			expr: &actionExpr{
				pos: position{line: 263, col: 23, offset: 6262},
				run: (*parser).callonMultiplicativeExpr1,
				expr: &seqExpr{
					pos: position{line: 263, col: 23, offset: 6262},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 263, col: 23, offset: 6262},
							label: "left",
							expr: &ruleRefExpr{
								pos:  position{line: 263, col: 28, offset: 6267},
								name: "UnaryExpr",
							},
						},
						&labeledExpr{
							pos:   position{line: 263, col: 38, offset: 6277},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 263, col: 43, offset: 6282},
								expr: &ruleRefExpr{
									pos:  position{line: 263, col: 43, offset: 6282},
									name: "MultiplicativeTail",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "MultiplicativeTail",
			pos:  position{line: 267, col: 1, offset: 6349},
			expr: &actionExpr{
				pos: position{line: 267, col: 23, offset: 6371},
				run: (*parser).callonMultiplicativeTail1,
				expr: &seqExpr{
					pos: position{line: 267, col: 23, offset: 6371},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 267, col: 23, offset: 6371},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 267, col: 25, offset: 6373},
							label: "op",
							expr: &choiceExpr{
								pos: position{line: 267, col: 30, offset: 6378},
								alternatives: []any{
									&litMatcher{
										pos:        position{line: 267, col: 30, offset: 6378},
										val:        "*",
										ignoreCase: false,
										want:       "\"*\"",
									},
									&litMatcher{
										pos:        position{line: 267, col: 36, offset: 6384},
										val:        "/",
										ignoreCase: false,
										want:       "\"/\"",
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 267, col: 42, offset: 6390},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 267, col: 44, offset: 6392},
							label: "right",
							expr: &ruleRefExpr{
								pos:  position{line: 267, col: 50, offset: 6398},
								name: "UnaryExpr",
							},
						},
					},
				},
			},
		},
		{
			name: "UnaryExpr",
			pos:  position{line: 271, col: 1, offset: 6482},
			expr: &choiceExpr{
				pos: position{line: 271, col: 14, offset: 6495},
				alternatives: []any{
					&ruleRefExpr{
						pos:  position{line: 271, col: 14, offset: 6495},
						name: "Primary",
					},
					&actionExpr{
						pos: position{line: 271, col: 24, offset: 6505},
						run: (*parser).callonUnaryExpr3,
						expr: &seqExpr{
							pos: position{line: 271, col: 24, offset: 6505},
							exprs: []any{
								&labeledExpr{
									pos:   position{line: 271, col: 24, offset: 6505},
									label: "op",
									expr: &choiceExpr{
										pos: position{line: 271, col: 29, offset: 6510},
										alternatives: []any{
											&litMatcher{
												pos:        position{line: 271, col: 29, offset: 6510},
												val:        "!",
												ignoreCase: false,
												want:       "\"!\"",
											},
											&litMatcher{
												pos:        position{line: 271, col: 35, offset: 6516},
												val:        "-",
												ignoreCase: false,
												want:       "\"-\"",
											},
										},
									},
								},
								&ruleRefExpr{
									pos:  position{line: 271, col: 41, offset: 6522},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 271, col: 43, offset: 6524},
									label: "inner",
									expr: &ruleRefExpr{
										pos:  position{line: 271, col: 49, offset: 6530},
										name: "UnaryExpr",
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Primary",
			pos:  position{line: 275, col: 1, offset: 6624},
			expr: &choiceExpr{
				pos: position{line: 275, col: 12, offset: 6635},
				alternatives: []any{
					&ruleRefExpr{
						pos:  position{line: 275, col: 12, offset: 6635},
						name: "ParenExpr",
					},
					&ruleRefExpr{
						pos:  position{line: 275, col: 24, offset: 6647},
						name: "ObjectLitNode",
					},
					&ruleRefExpr{
						pos:  position{line: 275, col: 40, offset: 6663},
						name: "ArrayLitNode",
					},
					&ruleRefExpr{
						pos:  position{line: 275, col: 55, offset: 6678},
						name: "StringLitNode",
					},
					&ruleRefExpr{
						pos:  position{line: 275, col: 71, offset: 6694},
						name: "MultilineStringLitNode",
					},
					&ruleRefExpr{
						pos:  position{line: 275, col: 96, offset: 6719},
						name: "NumberLitNode",
					},
					&ruleRefExpr{
						pos:  position{line: 275, col: 112, offset: 6735},
						name: "BoolLitNode",
					},
					&ruleRefExpr{
						pos:  position{line: 275, col: 126, offset: 6749},
						name: "NullLitNode",
					},
					&ruleRefExpr{
						pos:  position{line: 275, col: 140, offset: 6763},
						name: "NameExpression",
					},
				},
			},
		},
		{
			name: "ParenExpr",
			pos:  position{line: 277, col: 1, offset: 6779},
			expr: &actionExpr{
				pos: position{line: 277, col: 14, offset: 6792},
				run: (*parser).callonParenExpr1,
				expr: &seqExpr{
					pos: position{line: 277, col: 14, offset: 6792},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 277, col: 14, offset: 6792},
							val:        "(",
							ignoreCase: false,
							want:       "\"(\"",
						},
						&ruleRefExpr{
							pos:  position{line: 277, col: 18, offset: 6796},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 277, col: 20, offset: 6798},
							label: "e",
							expr: &ruleRefExpr{
								pos:  position{line: 277, col: 22, offset: 6800},
								name: "Value",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 277, col: 28, offset: 6806},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 277, col: 30, offset: 6808},
							val:        ")",
							ignoreCase: false,
							want:       "\")\"",
						},
					},
				},
			},
		},
		{
			name: "NameExpression",
			pos:  position{line: 281, col: 1, offset: 6832},
			expr: &choiceExpr{
				pos: position{line: 281, col: 19, offset: 6850},
				alternatives: []any{
					&ruleRefExpr{
						pos:  position{line: 281, col: 19, offset: 6850},
						name: "ModuleCall",
					},
					&ruleRefExpr{
						pos:  position{line: 281, col: 32, offset: 6863},
						name: "BareCall",
					},
					&ruleRefExpr{
						pos:  position{line: 281, col: 43, offset: 6874},
						name: "DotPath",
					},
					&ruleRefExpr{
						pos:  position{line: 281, col: 53, offset: 6884},
						name: "IdentValue",
					},
				},
			},
		},
		{
			name: "ModuleCall",
			pos:  position{line: 283, col: 1, offset: 6896},
			expr: &actionExpr{
				pos: position{line: 283, col: 15, offset: 6910},
				run: (*parser).callonModuleCall1,
				expr: &seqExpr{
					pos: position{line: 283, col: 15, offset: 6910},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 283, col: 15, offset: 6910},
							label: "mod",
							expr: &ruleRefExpr{
								pos:  position{line: 283, col: 19, offset: 6914},
								name: "IdentText",
							},
						},
						&litMatcher{
							pos:        position{line: 283, col: 29, offset: 6924},
							val:        ".",
							ignoreCase: false,
							want:       "\".\"",
						},
						&labeledExpr{
							pos:   position{line: 283, col: 33, offset: 6928},
							label: "fn",
							expr: &ruleRefExpr{
								pos:  position{line: 283, col: 36, offset: 6931},
								name: "IdentText",
							},
						},
						&litMatcher{
							pos:        position{line: 283, col: 46, offset: 6941},
							val:        "(",
							ignoreCase: false,
							want:       "\"(\"",
						},
						&ruleRefExpr{
							pos:  position{line: 283, col: 50, offset: 6945},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 283, col: 52, offset: 6947},
							label: "args",
							expr: &ruleRefExpr{
								pos:  position{line: 283, col: 57, offset: 6952},
								name: "CallArgs",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 283, col: 66, offset: 6961},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 283, col: 68, offset: 6963},
							val:        ")",
							ignoreCase: false,
							want:       "\")\"",
						},
					},
				},
			},
		},
		{
			name: "BareCall",
			pos:  position{line: 293, col: 1, offset: 7149},
			expr: &actionExpr{
				pos: position{line: 293, col: 13, offset: 7161},
				run: (*parser).callonBareCall1,
				expr: &seqExpr{
					pos: position{line: 293, col: 13, offset: 7161},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 293, col: 13, offset: 7161},
							label: "name",
							expr: &ruleRefExpr{
								pos:  position{line: 293, col: 18, offset: 7166},
								name: "IdentText",
							},
						},
						&litMatcher{
							pos:        position{line: 293, col: 28, offset: 7176},
							val:        "(",
							ignoreCase: false,
							want:       "\"(\"",
						},
						&ruleRefExpr{
							pos:  position{line: 293, col: 32, offset: 7180},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 293, col: 34, offset: 7182},
							label: "args",
							expr: &ruleRefExpr{
								pos:  position{line: 293, col: 39, offset: 7187},
								name: "CallArgs",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 293, col: 48, offset: 7196},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 293, col: 50, offset: 7198},
							val:        ")",
							ignoreCase: false,
							want:       "\")\"",
						},
					},
				},
			},
		},
		{
			name: "CallArgs",
			pos:  position{line: 302, col: 1, offset: 7339},
			expr: &actionExpr{
				pos: position{line: 302, col: 13, offset: 7351},
				run: (*parser).callonCallArgs1,
				expr: &labeledExpr{
					pos:   position{line: 302, col: 13, offset: 7351},
					label: "args",
					expr: &zeroOrOneExpr{
						pos: position{line: 302, col: 18, offset: 7356},
						expr: &seqExpr{
							pos: position{line: 302, col: 20, offset: 7358},
							exprs: []any{
								&labeledExpr{
									pos:   position{line: 302, col: 20, offset: 7358},
									label: "first",
									expr: &ruleRefExpr{
										pos:  position{line: 302, col: 26, offset: 7364},
										name: "Value",
									},
								},
								&labeledExpr{
									pos:   position{line: 302, col: 32, offset: 7370},
									label: "rest",
									expr: &zeroOrMoreExpr{
										pos: position{line: 302, col: 37, offset: 7375},
										expr: &actionExpr{
											pos: position{line: 302, col: 39, offset: 7377},
											run: (*parser).callonCallArgs9,
											expr: &seqExpr{
												pos: position{line: 302, col: 39, offset: 7377},
												exprs: []any{
													&ruleRefExpr{
														pos:  position{line: 302, col: 39, offset: 7377},
														name: "_",
													},
													&litMatcher{
														pos:        position{line: 302, col: 41, offset: 7379},
														val:        ",",
														ignoreCase: false,
														want:       "\",\"",
													},
													&ruleRefExpr{
														pos:  position{line: 302, col: 45, offset: 7383},
														name: "_",
													},
													&labeledExpr{
														pos:   position{line: 302, col: 47, offset: 7385},
														label: "v",
														expr: &ruleRefExpr{
															pos:  position{line: 302, col: 49, offset: 7387},
															name: "Value",
														},
													},
												},
											},
										},
									},
								},
								&ruleRefExpr{
									pos:  position{line: 302, col: 76, offset: 7414},
									name: "_",
								},
								&zeroOrOneExpr{
									pos: position{line: 302, col: 78, offset: 7416},
									expr: &litMatcher{
										pos:        position{line: 302, col: 78, offset: 7416},
										val:        ",",
										ignoreCase: false,
										want:       "\",\"",
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "DotPath",
			pos:  position{line: 315, col: 1, offset: 7647},
			expr: &actionExpr{
				pos: position{line: 315, col: 12, offset: 7658},
				run: (*parser).callonDotPath1,
				expr: &seqExpr{
					pos: position{line: 315, col: 12, offset: 7658},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 315, col: 12, offset: 7658},
							label: "root",
							expr: &ruleRefExpr{
								pos:  position{line: 315, col: 17, offset: 7663},
								name: "IdentText",
							},
						},
						&labeledExpr{
							pos:   position{line: 315, col: 27, offset: 7673},
							label: "segs",
							expr: &oneOrMoreExpr{
								pos: position{line: 315, col: 32, offset: 7678},
								expr: &ruleRefExpr{
									pos:  position{line: 315, col: 32, offset: 7678},
									name: "DotSegmentRule",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "DotSegmentRule",
			pos:  position{line: 324, col: 1, offset: 7842},
			expr: &choiceExpr{
				pos: position{line: 324, col: 19, offset: 7860},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 324, col: 19, offset: 7860},
						run: (*parser).callonDotSegmentRule2,
						expr: &seqExpr{
							pos: position{line: 324, col: 19, offset: 7860},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 324, col: 19, offset: 7860},
									val:        ".",
									ignoreCase: false,
									want:       "\".\"",
								},
								&labeledExpr{
									pos:   position{line: 324, col: 23, offset: 7864},
									label: "name",
									expr: &ruleRefExpr{
										pos:  position{line: 324, col: 28, offset: 7869},
										name: "IdentText",
									},
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 326, col: 5, offset: 7943},
						run: (*parser).callonDotSegmentRule7,
						expr: &seqExpr{
							pos: position{line: 326, col: 5, offset: 7943},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 326, col: 5, offset: 7943},
									val:        "[",
									ignoreCase: false,
									want:       "\"[\"",
								},
								&ruleRefExpr{
									pos:  position{line: 326, col: 9, offset: 7947},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 326, col: 11, offset: 7949},
									label: "key",
									expr: &ruleRefExpr{
										pos:  position{line: 326, col: 15, offset: 7953},
										name: "Value",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 326, col: 21, offset: 7959},
									name: "_",
								},
								&litMatcher{
									pos:        position{line: 326, col: 23, offset: 7961},
									val:        "]",
									ignoreCase: false,
									want:       "\"]\"",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "IdentValue",
			pos:  position{line: 330, col: 1, offset: 8026},
			expr: &actionExpr{
				pos: position{line: 330, col: 15, offset: 8040},
				run: (*parser).callonIdentValue1,
				expr: &labeledExpr{
					pos:   position{line: 330, col: 15, offset: 8040},
					label: "name",
					expr: &ruleRefExpr{
						pos:  position{line: 330, col: 20, offset: 8045},
						name: "IdentText",
					},
				},
			},
		},
		{
			name: "ObjectLitNode",
			pos:  position{line: 334, col: 1, offset: 8114},
			expr: &actionExpr{
				pos: position{line: 334, col: 18, offset: 8131},
				run: (*parser).callonObjectLitNode1,
				expr: &seqExpr{
					pos: position{line: 334, col: 18, offset: 8131},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 334, col: 18, offset: 8131},
							val:        "{",
							ignoreCase: false,
							want:       "\"{\"",
						},
						&ruleRefExpr{
							pos:  position{line: 334, col: 22, offset: 8135},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 334, col: 24, offset: 8137},
							label: "pairs",
							expr: &zeroOrMoreExpr{
								pos: position{line: 334, col: 30, offset: 8143},
								expr: &ruleRefExpr{
									pos:  position{line: 334, col: 30, offset: 8143},
									name: "Pair",
								},
							},
						},
						&litMatcher{
							pos:        position{line: 334, col: 36, offset: 8149},
							val:        "}",
							ignoreCase: false,
							want:       "\"}\"",
						},
					},
				},
			},
		},
		{
			name: "ArrayLitNode",
			pos:  position{line: 338, col: 1, offset: 8222},
			expr: &actionExpr{
				pos: position{line: 338, col: 17, offset: 8238},
				run: (*parser).callonArrayLitNode1,
				expr: &seqExpr{
					pos: position{line: 338, col: 17, offset: 8238},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 338, col: 17, offset: 8238},
							val:        "[",
							ignoreCase: false,
							want:       "\"[\"",
						},
						&ruleRefExpr{
							pos:  position{line: 338, col: 21, offset: 8242},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 338, col: 23, offset: 8244},
							label: "elems",
							expr: &zeroOrOneExpr{
								pos: position{line: 338, col: 29, offset: 8250},
								expr: &ruleRefExpr{
									pos:  position{line: 338, col: 29, offset: 8250},
									name: "ArrayElems",
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 338, col: 41, offset: 8262},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 338, col: 43, offset: 8264},
							val:        "]",
							ignoreCase: false,
							want:       "\"]\"",
						},
					},
				},
			},
		},
		{
			name: "ArrayElems",
			pos:  position{line: 345, col: 1, offset: 8396},
			expr: &actionExpr{
				pos: position{line: 345, col: 15, offset: 8410},
				run: (*parser).callonArrayElems1,
				expr: &seqExpr{
					pos: position{line: 345, col: 15, offset: 8410},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 345, col: 15, offset: 8410},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 345, col: 21, offset: 8416},
								name: "Value",
							},
						},
						&labeledExpr{
							pos:   position{line: 345, col: 27, offset: 8422},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 345, col: 32, offset: 8427},
								expr: &actionExpr{
									pos: position{line: 345, col: 34, offset: 8429},
									run: (*parser).callonArrayElems7,
									expr: &seqExpr{
										pos: position{line: 345, col: 34, offset: 8429},
										exprs: []any{
											&ruleRefExpr{
												pos:  position{line: 345, col: 34, offset: 8429},
												name: "_",
											},
											&litMatcher{
												pos:        position{line: 345, col: 36, offset: 8431},
												val:        ",",
												ignoreCase: false,
												want:       "\",\"",
											},
											&ruleRefExpr{
												pos:  position{line: 345, col: 40, offset: 8435},
												name: "_",
											},
											&labeledExpr{
												pos:   position{line: 345, col: 42, offset: 8437},
												label: "v",
												expr: &ruleRefExpr{
													pos:  position{line: 345, col: 44, offset: 8439},
													name: "Value",
												},
											},
										},
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 345, col: 71, offset: 8466},
							name: "_",
						},
						&zeroOrOneExpr{
							pos: position{line: 345, col: 73, offset: 8468},
							expr: &litMatcher{
								pos:        position{line: 345, col: 73, offset: 8468},
								val:        ",",
								ignoreCase: false,
								want:       "\",\"",
							},
						},
					},
				},
			},
		},
		{
			name: "StringLitNode",
			pos:  position{line: 352, col: 1, offset: 8553},
			expr: &actionExpr{
				pos: position{line: 352, col: 18, offset: 8570},
				run: (*parser).callonStringLitNode1,
				expr: &seqExpr{
					pos: position{line: 352, col: 18, offset: 8570},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 352, col: 18, offset: 8570},
							val:        "'",
							ignoreCase: false,
							want:       "\"'\"",
						},
						&labeledExpr{
							pos:   position{line: 352, col: 22, offset: 8574},
							label: "body",
							expr: &ruleRefExpr{
								pos:  position{line: 352, col: 27, offset: 8579},
								name: "StringBody",
							},
						},
						&litMatcher{
							pos:        position{line: 352, col: 38, offset: 8590},
							val:        "'",
							ignoreCase: false,
							want:       "\"'\"",
						},
					},
				},
			},
		},
		{
			name: "StringBody",
			pos:  position{line: 356, col: 1, offset: 8658},
			expr: &actionExpr{
				pos: position{line: 356, col: 15, offset: 8672},
				run: (*parser).callonStringBody1,
				expr: &zeroOrMoreExpr{
					pos: position{line: 356, col: 15, offset: 8672},
					expr: &choiceExpr{
						pos: position{line: 356, col: 17, offset: 8674},
						alternatives: []any{
							&seqExpr{
								pos: position{line: 356, col: 17, offset: 8674},
								exprs: []any{
									&notExpr{
										pos: position{line: 356, col: 17, offset: 8674},
										expr: &litMatcher{
											pos:        position{line: 356, col: 18, offset: 8675},
											val:        "'",
											ignoreCase: false,
											want:       "\"'\"",
										},
									},
									&notExpr{
										pos: position{line: 356, col: 22, offset: 8679},
										expr: &litMatcher{
											pos:        position{line: 356, col: 23, offset: 8680},
											val:        "\\",
											ignoreCase: false,
											want:       "\"\\\\\"",
										},
									},
									&notExpr{
										pos: position{line: 356, col: 28, offset: 8685},
										expr: &litMatcher{
											pos:        position{line: 356, col: 29, offset: 8686},
											val:        "\n",
											ignoreCase: false,
											want:       "\"\\n\"",
										},
									},
									&notExpr{
										pos: position{line: 356, col: 34, offset: 8691},
										expr: &litMatcher{
											pos:        position{line: 356, col: 35, offset: 8692},
											val:        "\r",
											ignoreCase: false,
											want:       "\"\\r\"",
										},
									},
									&anyMatcher{
										line: 356, col: 40, offset: 8697,
									},
								},
							},
							&seqExpr{
								pos: position{line: 356, col: 44, offset: 8701},
								exprs: []any{
									&litMatcher{
										pos:        position{line: 356, col: 44, offset: 8701},
										val:        "\\",
										ignoreCase: false,
										want:       "\"\\\\\"",
									},
									&anyMatcher{
										line: 356, col: 49, offset: 8706,
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "MultilineStringLitNode",
			pos:  position{line: 360, col: 1, offset: 8759},
			expr: &actionExpr{
				pos: position{line: 360, col: 27, offset: 8785},
				run: (*parser).callonMultilineStringLitNode1,
				expr: &seqExpr{
					pos: position{line: 360, col: 27, offset: 8785},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 360, col: 27, offset: 8785},
							val:        "`",
							ignoreCase: false,
							want:       "\"`\"",
						},
						&ruleRefExpr{
							pos:  position{line: 360, col: 31, offset: 8789},
							name: "MultilineBody",
						},
						&litMatcher{
							pos:        position{line: 360, col: 45, offset: 8803},
							val:        "`",
							ignoreCase: false,
							want:       "\"`\"",
						},
					},
				},
			},
		},
		{
			name: "MultilineBody",
			pos:  position{line: 365, col: 1, offset: 8927},
			expr: &zeroOrMoreExpr{
				pos: position{line: 365, col: 18, offset: 8944},
				expr: &seqExpr{
					pos: position{line: 365, col: 20, offset: 8946},
					exprs: []any{
						&notExpr{
							pos: position{line: 365, col: 20, offset: 8946},
							expr: &litMatcher{
								pos:        position{line: 365, col: 21, offset: 8947},
								val:        "`",
								ignoreCase: false,
								want:       "\"`\"",
							},
						},
						&anyMatcher{
							line: 365, col: 25, offset: 8951,
						},
					},
				},
			},
		},
		{
			name: "NumberLitNode",
			pos:  position{line: 367, col: 1, offset: 8957},
			expr: &actionExpr{
				pos: position{line: 367, col: 18, offset: 8974},
				run: (*parser).callonNumberLitNode1,
				expr: &seqExpr{
					pos: position{line: 367, col: 20, offset: 8976},
					exprs: []any{
						&zeroOrOneExpr{
							pos: position{line: 367, col: 20, offset: 8976},
							expr: &litMatcher{
								pos:        position{line: 367, col: 20, offset: 8976},
								val:        "-",
								ignoreCase: false,
								want:       "\"-\"",
							},
						},
						&oneOrMoreExpr{
							pos: position{line: 367, col: 25, offset: 8981},
							expr: &charClassMatcher{
								pos:        position{line: 367, col: 25, offset: 8981},
								val:        "[0-9]",
								ranges:     []rune{'0', '9'},
								ignoreCase: false,
								inverted:   false,
							},
						},
						&zeroOrOneExpr{
							pos: position{line: 367, col: 32, offset: 8988},
							expr: &seqExpr{
								pos: position{line: 367, col: 34, offset: 8990},
								exprs: []any{
									&litMatcher{
										pos:        position{line: 367, col: 34, offset: 8990},
										val:        ".",
										ignoreCase: false,
										want:       "\".\"",
									},
									&oneOrMoreExpr{
										pos: position{line: 367, col: 38, offset: 8994},
										expr: &charClassMatcher{
											pos:        position{line: 367, col: 38, offset: 8994},
											val:        "[0-9]",
											ranges:     []rune{'0', '9'},
											ignoreCase: false,
											inverted:   false,
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "BoolLitNode",
			pos:  position{line: 387, col: 1, offset: 9362},
			expr: &choiceExpr{
				pos: position{line: 387, col: 16, offset: 9377},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 387, col: 16, offset: 9377},
						run: (*parser).callonBoolLitNode2,
						expr: &seqExpr{
							pos: position{line: 387, col: 16, offset: 9377},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 387, col: 16, offset: 9377},
									val:        "true",
									ignoreCase: false,
									want:       "\"true\"",
								},
								&notExpr{
									pos: position{line: 387, col: 23, offset: 9384},
									expr: &ruleRefExpr{
										pos:  position{line: 387, col: 24, offset: 9385},
										name: "IdentChar",
									},
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 389, col: 5, offset: 9449},
						run: (*parser).callonBoolLitNode7,
						expr: &seqExpr{
							pos: position{line: 389, col: 5, offset: 9449},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 389, col: 5, offset: 9449},
									val:        "false",
									ignoreCase: false,
									want:       "\"false\"",
								},
								&notExpr{
									pos: position{line: 389, col: 13, offset: 9457},
									expr: &ruleRefExpr{
										pos:  position{line: 389, col: 14, offset: 9458},
										name: "IdentChar",
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "NullLitNode",
			pos:  position{line: 393, col: 1, offset: 9522},
			expr: &actionExpr{
				pos: position{line: 393, col: 16, offset: 9537},
				run: (*parser).callonNullLitNode1,
				expr: &seqExpr{
					pos: position{line: 393, col: 16, offset: 9537},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 393, col: 16, offset: 9537},
							val:        "null",
							ignoreCase: false,
							want:       "\"null\"",
						},
						&notExpr{
							pos: position{line: 393, col: 23, offset: 9544},
							expr: &ruleRefExpr{
								pos:  position{line: 393, col: 24, offset: 9545},
								name: "IdentChar",
							},
						},
					},
				},
			},
		},
		{
			name: "IdentText",
			pos:  position{line: 402, col: 1, offset: 9966},
			expr: &actionExpr{
				pos: position{line: 402, col: 14, offset: 9979},
				run: (*parser).callonIdentText1,
				expr: &seqExpr{
					pos: position{line: 402, col: 16, offset: 9981},
					exprs: []any{
						&zeroOrOneExpr{
							pos: position{line: 402, col: 16, offset: 9981},
							expr: &litMatcher{
								pos:        position{line: 402, col: 16, offset: 9981},
								val:        "@",
								ignoreCase: false,
								want:       "\"@\"",
							},
						},
						&charClassMatcher{
							pos:        position{line: 402, col: 21, offset: 9986},
							val:        "[a-zA-Z]",
							ranges:     []rune{'a', 'z', 'A', 'Z'},
							ignoreCase: false,
							inverted:   false,
						},
						&zeroOrMoreExpr{
							pos: position{line: 402, col: 30, offset: 9995},
							expr: &choiceExpr{
								pos: position{line: 402, col: 32, offset: 9997},
								alternatives: []any{
									&seqExpr{
										pos: position{line: 402, col: 32, offset: 9997},
										exprs: []any{
											&oneOrMoreExpr{
												pos: position{line: 402, col: 32, offset: 9997},
												expr: &litMatcher{
													pos:        position{line: 402, col: 32, offset: 9997},
													val:        "-",
													ignoreCase: false,
													want:       "\"-\"",
												},
											},
											&charClassMatcher{
												pos:        position{line: 402, col: 37, offset: 10002},
												val:        "[a-zA-Z0-9]",
												ranges:     []rune{'a', 'z', 'A', 'Z', '0', '9'},
												ignoreCase: false,
												inverted:   false,
											},
										},
									},
									&charClassMatcher{
										pos:        position{line: 402, col: 51, offset: 10016},
										val:        "[a-zA-Z0-9]",
										ranges:     []rune{'a', 'z', 'A', 'Z', '0', '9'},
										ignoreCase: false,
										inverted:   false,
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "IdentChar",
			pos:  position{line: 406, col: 1, offset: 10066},
			expr: &charClassMatcher{
				pos:        position{line: 406, col: 14, offset: 10079},
				val:        "[a-zA-Z0-9_-]",
				chars:      []rune{'_', '-'},
				ranges:     []rune{'a', 'z', 'A', 'Z', '0', '9'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "_",
			pos:  position{line: 409, col: 1, offset: 10095},
			expr: &zeroOrMoreExpr{
				pos: position{line: 409, col: 6, offset: 10100},
				expr: &choiceExpr{
					pos: position{line: 409, col: 8, offset: 10102},
					alternatives: []any{
						&charClassMatcher{
							pos:        position{line: 409, col: 8, offset: 10102},
							val:        "[ \\t\\r\\n]",
							chars:      []rune{' ', '\t', '\r', '\n'},
							ignoreCase: false,
							inverted:   false,
						},
						&ruleRefExpr{
							pos:  position{line: 409, col: 20, offset: 10114},
							name: "Comment",
						},
					},
				},
			},
		},
		{
			name: "Comment",
			pos:  position{line: 411, col: 1, offset: 10126},
			expr: &seqExpr{
				pos: position{line: 411, col: 12, offset: 10137},
				exprs: []any{
					&litMatcher{
						pos:        position{line: 411, col: 12, offset: 10137},
						val:        "#",
						ignoreCase: false,
						want:       "\"#\"",
					},
					&zeroOrMoreExpr{
						pos: position{line: 411, col: 16, offset: 10141},
						expr: &charClassMatcher{
							pos:        position{line: 411, col: 16, offset: 10141},
							val:        "[^\\r\\n]",
							chars:      []rune{'\r', '\n'},
							ignoreCase: false,
							inverted:   true,
						},
					},
				},
			},
		},
		{
			name: "EOF",
			pos:  position{line: 413, col: 1, offset: 10151},
			expr: &notExpr{
				pos: position{line: 413, col: 8, offset: 10158},
				expr: &anyMatcher{
					line: 413, col: 9, offset: 10159,
				},
			},
		},
	},
}

func (c *current) onFile1(pairs any) (any, error) {
	body := &ObjectLit{S: c.span(), Fields: fieldSlice(pairs)}
	f := &File{S: c.span(), Body: body}
	if path, ok := c.globalStore["file"].(string); ok {
		f.Path = path
	}
	return f, nil
}

func (p *parser) callonFile1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFile1(stack["pairs"])
}

func (c *current) onPair1(key, value any) (any, error) {
	fk := key.(FieldKey)
	return &Field{S: fk.S, Key: fk, Value: value.(Expr)}, nil
}

func (p *parser) callonPair1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onPair1(stack["key"], stack["value"])
}

func (c *current) onIdentKey1(name any) (any, error) {
	return FieldKey{S: c.span(), Kind: FieldIdent, Name: name.(string)}, nil
}

func (p *parser) callonIdentKey1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIdentKey1(stack["name"])
}

func (c *current) onStringKey1(s any) (any, error) {
	sl := s.(*StringLit)
	return FieldKey{S: sl.S, Kind: FieldString, String: sl.Value}, nil
}

func (p *parser) callonStringKey1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onStringKey1(stack["s"])
}

func (c *current) onExpr1(left, rest any) (any, error) {
	return foldInfix(left.(Expr), rest), nil
}

func (p *parser) callonExpr1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onExpr1(stack["left"], stack["rest"])
}

func (c *current) onOrTail1(right any) (any, error) {
	return infixTail{op: "||", right: right.(Expr)}, nil
}

func (p *parser) callonOrTail1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onOrTail1(stack["right"])
}

func (c *current) onAndExpr1(left, rest any) (any, error) {
	return foldInfix(left.(Expr), rest), nil
}

func (p *parser) callonAndExpr1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAndExpr1(stack["left"], stack["rest"])
}

func (c *current) onAndTail1(right any) (any, error) {
	return infixTail{op: "&&", right: right.(Expr)}, nil
}

func (p *parser) callonAndTail1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAndTail1(stack["right"])
}

func (c *current) onEqualityExpr1(left, rest any) (any, error) {
	return foldInfix(left.(Expr), rest), nil
}

func (p *parser) callonEqualityExpr1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onEqualityExpr1(stack["left"], stack["rest"])
}

func (c *current) onEqualityTail1(op, right any) (any, error) {
	return infixTail{op: string(op.([]byte)), right: right.(Expr)}, nil
}

func (p *parser) callonEqualityTail1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onEqualityTail1(stack["op"], stack["right"])
}

func (c *current) onComparisonExpr1(left, rest any) (any, error) {
	return foldInfix(left.(Expr), rest), nil
}

func (p *parser) callonComparisonExpr1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onComparisonExpr1(stack["left"], stack["rest"])
}

func (c *current) onComparisonTail1(op, right any) (any, error) {
	return infixTail{op: string(op.([]byte)), right: right.(Expr)}, nil
}

func (p *parser) callonComparisonTail1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onComparisonTail1(stack["op"], stack["right"])
}

func (c *current) onAdditiveExpr1(left, rest any) (any, error) {
	return foldInfix(left.(Expr), rest), nil
}

func (p *parser) callonAdditiveExpr1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAdditiveExpr1(stack["left"], stack["rest"])
}

func (c *current) onAdditiveTail1(op, right any) (any, error) {
	return infixTail{op: string(op.([]byte)), right: right.(Expr)}, nil
}

func (p *parser) callonAdditiveTail1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAdditiveTail1(stack["op"], stack["right"])
}

func (c *current) onMultiplicativeExpr1(left, rest any) (any, error) {
	return foldInfix(left.(Expr), rest), nil
}

func (p *parser) callonMultiplicativeExpr1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMultiplicativeExpr1(stack["left"], stack["rest"])
}

func (c *current) onMultiplicativeTail1(op, right any) (any, error) {
	return infixTail{op: string(op.([]byte)), right: right.(Expr)}, nil
}

func (p *parser) callonMultiplicativeTail1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMultiplicativeTail1(stack["op"], stack["right"])
}

func (c *current) onUnaryExpr3(op, inner any) (any, error) {
	return &Prefix{S: c.span(), Op: string(op.([]byte)), Expr: inner.(Expr)}, nil
}

func (p *parser) callonUnaryExpr3() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onUnaryExpr3(stack["op"], stack["inner"])
}

func (c *current) onParenExpr1(e any) (any, error) {
	return e, nil
}

func (p *parser) callonParenExpr1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onParenExpr1(stack["e"])
}

func (c *current) onModuleCall1(mod, fn, args any) (any, error) {
	span := c.span()
	return &Call{
		S:      span,
		Module: &Ident{S: span, Name: mod.(string)},
		Func:   &Ident{S: span, Name: fn.(string)},
		Args:   exprSlice(args),
	}, nil
}

func (p *parser) callonModuleCall1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onModuleCall1(stack["mod"], stack["fn"], stack["args"])
}

func (c *current) onBareCall1(name, args any) (any, error) {
	span := c.span()
	return &Call{
		S:      span,
		Callee: &Ident{S: span, Name: name.(string)},
		Args:   exprSlice(args),
	}, nil
}

func (p *parser) callonBareCall1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBareCall1(stack["name"], stack["args"])
}

func (c *current) onCallArgs9(v any) (any, error) {
	return v, nil
}

func (p *parser) callonCallArgs9() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCallArgs9(stack["v"])
}

func (c *current) onCallArgs1(args any) (any, error) {
	if args == nil {
		return []any{}, nil
	}
	parts := args.([]any)
	first := parts[0]
	rest := parts[1].([]any)
	out := make([]any, 0, 1+len(rest))
	out = append(out, first)
	out = append(out, rest...)
	return out, nil
}

func (p *parser) callonCallArgs1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCallArgs1(stack["args"])
}

func (c *current) onDotPath1(root, segs any) (any, error) {
	span := c.span()
	return &DotPath{
		S:        span,
		Root:     &Ident{S: span, Name: root.(string)},
		Segments: dotSegments(segs),
	}, nil
}

func (p *parser) callonDotPath1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDotPath1(stack["root"], stack["segs"])
}

func (c *current) onDotSegmentRule2(name any) (any, error) {
	return DotSegment{S: c.span(), Name: name.(string)}, nil
}

func (p *parser) callonDotSegmentRule2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDotSegmentRule2(stack["name"])
}

func (c *current) onDotSegmentRule7(key any) (any, error) {
	return DotSegment{S: c.span(), Index: key.(Expr)}, nil
}

func (p *parser) callonDotSegmentRule7() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDotSegmentRule7(stack["key"])
}

func (c *current) onIdentValue1(name any) (any, error) {
	return &Ident{S: c.span(), Name: name.(string)}, nil
}

func (p *parser) callonIdentValue1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIdentValue1(stack["name"])
}

func (c *current) onObjectLitNode1(pairs any) (any, error) {
	return &ObjectLit{S: c.span(), Fields: fieldSlice(pairs)}, nil
}

func (p *parser) callonObjectLitNode1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onObjectLitNode1(stack["pairs"])
}

func (c *current) onArrayLitNode1(elems any) (any, error) {
	if elems == nil {
		return &ArrayLit{S: c.span()}, nil
	}
	return &ArrayLit{S: c.span(), Elements: exprSlice(elems)}, nil
}

func (p *parser) callonArrayLitNode1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onArrayLitNode1(stack["elems"])
}

func (c *current) onArrayElems7(v any) (any, error) {
	return v, nil
}

func (p *parser) callonArrayElems7() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onArrayElems7(stack["v"])
}

func (c *current) onArrayElems1(first, rest any) (any, error) {
	out := []any{first}
	out = append(out, rest.([]any)...)
	return out, nil
}

func (p *parser) callonArrayElems1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onArrayElems1(stack["first"], stack["rest"])
}

func (c *current) onStringLitNode1(body any) (any, error) {
	return &StringLit{S: c.span(), Value: body.(string)}, nil
}

func (p *parser) callonStringLitNode1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onStringLitNode1(stack["body"])
}

func (c *current) onStringBody1() (any, error) {
	return unquoteSingle(string(c.text)), nil
}

func (p *parser) callonStringBody1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onStringBody1()
}

func (c *current) onMultilineStringLitNode1() (any, error) {
	val, err := processMultiline(c.text, c.pos.col)
	return &StringLit{S: c.span(), Value: val, Multiline: true}, err
}

func (p *parser) callonMultilineStringLitNode1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMultilineStringLitNode1()
}

func (c *current) onNumberLitNode1() (any, error) {
	raw := string(c.text)
	n := &NumberLit{S: c.span(), Value: raw}
	if strings.ContainsRune(raw, '.') {
		f, err := strconv.ParseFloat(raw, 64)
		if err != nil {
			return nil, err
		}
		n.IsFloat = true
		n.ParsedFloat = f
	} else {
		i, err := strconv.ParseInt(raw, 10, 64)
		if err != nil {
			return nil, err
		}
		n.ParsedInt = i
	}
	return n, nil
}

func (p *parser) callonNumberLitNode1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNumberLitNode1()
}

func (c *current) onBoolLitNode2() (any, error) {
	return &BoolLit{S: c.span(), Value: true}, nil
}

func (p *parser) callonBoolLitNode2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBoolLitNode2()
}

func (c *current) onBoolLitNode7() (any, error) {
	return &BoolLit{S: c.span(), Value: false}, nil
}

func (p *parser) callonBoolLitNode7() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBoolLitNode7()
}

func (c *current) onNullLitNode1() (any, error) {
	return &NullLit{S: c.span()}, nil
}

func (p *parser) callonNullLitNode1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNullLitNode1()
}

func (c *current) onIdentText1() (any, error) {
	return string(c.text), nil
}

func (p *parser) callonIdentText1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIdentText1()
}

var (
	// errNoRule is returned when the grammar to parse has no rule.
	errNoRule = errors.New("grammar has no rule")

	// errInvalidEntrypoint is returned when the specified entrypoint rule
	// does not exit.
	errInvalidEntrypoint = errors.New("invalid entrypoint")

	// errInvalidEncoding is returned when the source is not properly
	// utf8-encoded.
	errInvalidEncoding = errors.New("invalid encoding")

	// errMaxExprCnt is used to signal that the maximum number of
	// expressions have been parsed.
	errMaxExprCnt = errors.New("max number of expressions parsed")
)

// Option is a function that can set an option on the parser. It returns
// the previous setting as an Option.
type Option func(*parser) Option

// MaxExpressions creates an Option to stop parsing after the provided
// number of expressions have been parsed, if the value is 0 then the parser will
// parse for as many steps as needed (possibly an infinite number).
//
// The default for maxExprCnt is 0.
func MaxExpressions(maxExprCnt uint64) Option {
	return func(p *parser) Option {
		oldMaxExprCnt := p.maxExprCnt
		p.maxExprCnt = maxExprCnt
		return MaxExpressions(oldMaxExprCnt)
	}
}

// Entrypoint creates an Option to set the rule name to use as entrypoint.
// The rule name must have been specified in the -alternate-entrypoints
// if generating the parser with the -optimize-grammar flag, otherwise
// it may have been optimized out. Passing an empty string sets the
// entrypoint to the first rule in the grammar.
//
// The default is to start parsing at the first rule in the grammar.
func Entrypoint(ruleName string) Option {
	return func(p *parser) Option {
		oldEntrypoint := p.entrypoint
		p.entrypoint = ruleName
		if ruleName == "" {
			p.entrypoint = g.rules[0].name
		}
		return Entrypoint(oldEntrypoint)
	}
}

// Statistics adds a user provided Stats struct to the parser to allow
// the user to process the results after the parsing has finished.
// Also the key for the "no match" counter is set.
//
// Example usage:
//
//	input := "input"
//	stats := Stats{}
//	_, err := Parse("input-file", []byte(input), Statistics(&stats, "no match"))
//	if err != nil {
//	    log.Panicln(err)
//	}
//	b, err := json.MarshalIndent(stats.ChoiceAltCnt, "", "  ")
//	if err != nil {
//	    log.Panicln(err)
//	}
//	fmt.Println(string(b))
func Statistics(stats *Stats, choiceNoMatch string) Option {
	return func(p *parser) Option {
		oldStats := p.Stats
		p.Stats = stats
		oldChoiceNoMatch := p.choiceNoMatch
		p.choiceNoMatch = choiceNoMatch
		if p.Stats.ChoiceAltCnt == nil {
			p.Stats.ChoiceAltCnt = make(map[string]map[string]int)
		}
		return Statistics(oldStats, oldChoiceNoMatch)
	}
}

// Debug creates an Option to set the debug flag to b. When set to true,
// debugging information is printed to stdout while parsing.
//
// The default is false.
func Debug(b bool) Option {
	return func(p *parser) Option {
		old := p.debug
		p.debug = b
		return Debug(old)
	}
}

// Memoize creates an Option to set the memoize flag to b. When set to true,
// the parser will cache all results so each expression is evaluated only
// once. This guarantees linear parsing time even for pathological cases,
// at the expense of more memory and slower times for typical cases.
//
// The default is false.
func Memoize(b bool) Option {
	return func(p *parser) Option {
		old := p.memoize
		p.memoize = b
		return Memoize(old)
	}
}

// AllowInvalidUTF8 creates an Option to allow invalid UTF-8 bytes.
// Every invalid UTF-8 byte is treated as a utf8.RuneError (U+FFFD)
// by character class matchers and is matched by the any matcher.
// The returned matched value, c.text and c.offset are NOT affected.
//
// The default is false.
func AllowInvalidUTF8(b bool) Option {
	return func(p *parser) Option {
		old := p.allowInvalidUTF8
		p.allowInvalidUTF8 = b
		return AllowInvalidUTF8(old)
	}
}

// Recover creates an Option to set the recover flag to b. When set to
// true, this causes the parser to recover from panics and convert it
// to an error. Setting it to false can be useful while debugging to
// access the full stack trace.
//
// The default is true.
func Recover(b bool) Option {
	return func(p *parser) Option {
		old := p.recover
		p.recover = b
		return Recover(old)
	}
}

// GlobalStore creates an Option to set a key to a certain value in
// the globalStore.
func GlobalStore(key string, value any) Option {
	return func(p *parser) Option {
		old := p.cur.globalStore[key]
		p.cur.globalStore[key] = value
		return GlobalStore(key, old)
	}
}

// InitState creates an Option to set a key to a certain value in
// the global "state" store.
func InitState(key string, value any) Option {
	return func(p *parser) Option {
		old := p.cur.state[key]
		p.cur.state[key] = value
		return InitState(key, old)
	}
}

// ParseFile parses the file identified by filename.
func ParseFile(filename string, opts ...Option) (i any, err error) {
	f, err := os.Open(filename)
	if err != nil {
		return nil, err
	}
	defer func() {
		if closeErr := f.Close(); closeErr != nil {
			err = closeErr
		}
	}()
	return ParseReader(filename, f, opts...)
}

// ParseReader parses the data from r using filename as information in the
// error messages.
func ParseReader(filename string, r io.Reader, opts ...Option) (any, error) {
	b, err := io.ReadAll(r)
	if err != nil {
		return nil, err
	}

	return Parse(filename, b, opts...)
}

// Parse parses the data from b using filename as information in the
// error messages.
func Parse(filename string, b []byte, opts ...Option) (any, error) {
	return newParser(filename, b, opts...).parse(g)
}

// position records a position in the text.
type position struct {
	line, col, offset int
}

func (p position) String() string {
	return strconv.Itoa(p.line) + ":" + strconv.Itoa(p.col) + " [" + strconv.Itoa(p.offset) + "]"
}

// savepoint stores all state required to go back to this point in the
// parser.
type savepoint struct {
	position
	rn rune
	w  int
}

type current struct {
	pos  position // start position of the match
	text []byte   // raw text of the match

	// state is a store for arbitrary key,value pairs that the user wants to be
	// tied to the backtracking of the parser.
	// This is always rolled back if a parsing rule fails.
	state storeDict

	// globalStore is a general store for the user to store arbitrary key-value
	// pairs that they need to manage and that they do not want tied to the
	// backtracking of the parser. This is only modified by the user and never
	// rolled back by the parser. It is always up to the user to keep this in a
	// consistent state.
	globalStore storeDict
}

type storeDict map[string]any

// the AST types...

type grammar struct {
	pos   position
	rules []*rule
}

type rule struct {
	pos         position
	name        string
	displayName string
	expr        any
}

type choiceExpr struct {
	pos          position
	alternatives []any
}

type actionExpr struct {
	pos  position
	expr any
	run  func(*parser) (any, error)
}

type recoveryExpr struct {
	pos          position
	expr         any
	recoverExpr  any
	failureLabel []string
}

type seqExpr struct {
	pos   position
	exprs []any
}

type throwExpr struct {
	pos   position
	label string
}

type labeledExpr struct {
	pos   position
	label string
	expr  any
}

type expr struct {
	pos  position
	expr any
}

type (
	andExpr        expr
	notExpr        expr
	zeroOrOneExpr  expr
	zeroOrMoreExpr expr
	oneOrMoreExpr  expr
)

type ruleRefExpr struct {
	pos  position
	name string
}

type stateCodeExpr struct {
	pos position
	run func(*parser) error
}

type andCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type notCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type litMatcher struct {
	pos        position
	val        string
	ignoreCase bool
	want       string
}

type charClassMatcher struct {
	pos             position
	val             string
	basicLatinChars [128]bool
	chars           []rune
	ranges          []rune
	classes         []*unicode.RangeTable
	ignoreCase      bool
	inverted        bool
}

type anyMatcher position

// errList cumulates the errors found by the parser.
type errList []error

func (e *errList) add(err error) {
	*e = append(*e, err)
}

func (e errList) err() error {
	if len(e) == 0 {
		return nil
	}
	e.dedupe()
	return e
}

func (e *errList) dedupe() {
	var cleaned []error
	set := make(map[string]bool)
	for _, err := range *e {
		if msg := err.Error(); !set[msg] {
			set[msg] = true
			cleaned = append(cleaned, err)
		}
	}
	*e = cleaned
}

func (e errList) Error() string {
	switch len(e) {
	case 0:
		return ""
	case 1:
		return e[0].Error()
	default:
		var buf bytes.Buffer

		for i, err := range e {
			if i > 0 {
				buf.WriteRune('\n')
			}
			buf.WriteString(err.Error())
		}
		return buf.String()
	}
}

// parserError wraps an error with a prefix indicating the rule in which
// the error occurred. The original error is stored in the Inner field.
type parserError struct {
	Inner    error
	pos      position
	prefix   string
	expected []string
}

// Error returns the error message.
func (p *parserError) Error() string {
	return p.prefix + ": " + p.Inner.Error()
}

// newParser creates a parser with the specified input source and options.
func newParser(filename string, b []byte, opts ...Option) *parser {
	stats := Stats{
		ChoiceAltCnt: make(map[string]map[string]int),
	}

	p := &parser{
		filename: filename,
		errs:     new(errList),
		data:     b,
		pt:       savepoint{position: position{line: 1}},
		recover:  true,
		cur: current{
			state:       make(storeDict),
			globalStore: make(storeDict),
		},
		maxFailPos:      position{col: 1, line: 1},
		maxFailExpected: make([]string, 0, 20),
		Stats:           &stats,
		// start rule is rule [0] unless an alternate entrypoint is specified
		entrypoint: g.rules[0].name,
	}
	p.setOptions(opts)

	if p.maxExprCnt == 0 {
		p.maxExprCnt = math.MaxUint64
	}

	return p
}

// setOptions applies the options to the parser.
func (p *parser) setOptions(opts []Option) {
	for _, opt := range opts {
		opt(p)
	}
}

type resultTuple struct {
	v   any
	b   bool
	end savepoint
}

const choiceNoMatch = -1

// Stats stores some statistics, gathered during parsing
type Stats struct {
	// ExprCnt counts the number of expressions processed during parsing
	// This value is compared to the maximum number of expressions allowed
	// (set by the MaxExpressions option).
	ExprCnt uint64

	// ChoiceAltCnt is used to count for each ordered choice expression,
	// which alternative is used how may times.
	// These numbers allow to optimize the order of the ordered choice expression
	// to increase the performance of the parser
	//
	// The outer key of ChoiceAltCnt is composed of the name of the rule as well
	// as the line and the column of the ordered choice.
	// The inner key of ChoiceAltCnt is the number (one-based) of the matching alternative.
	// For each alternative the number of matches are counted. If an ordered choice does not
	// match, a special counter is incremented. The name of this counter is set with
	// the parser option Statistics.
	// For an alternative to be included in ChoiceAltCnt, it has to match at least once.
	ChoiceAltCnt map[string]map[string]int
}

type parser struct {
	filename string
	pt       savepoint
	cur      current

	data []byte
	errs *errList

	depth   int
	recover bool
	debug   bool

	memoize bool
	// memoization table for the packrat algorithm:
	// map[offset in source] map[expression or rule] {value, match}
	memo map[int]map[any]resultTuple

	// rules table, maps the rule identifier to the rule node
	rules map[string]*rule
	// variables stack, map of label to value
	vstack []map[string]any
	// rule stack, allows identification of the current rule in errors
	rstack []*rule

	// parse fail
	maxFailPos            position
	maxFailExpected       []string
	maxFailInvertExpected bool

	// max number of expressions to be parsed
	maxExprCnt uint64
	// entrypoint for the parser
	entrypoint string

	allowInvalidUTF8 bool

	*Stats

	choiceNoMatch string
	// recovery expression stack, keeps track of the currently available recovery expression, these are traversed in reverse
	recoveryStack []map[string]any
}

// push a variable set on the vstack.
func (p *parser) pushV() {
	if cap(p.vstack) == len(p.vstack) {
		// create new empty slot in the stack
		p.vstack = append(p.vstack, nil)
	} else {
		// slice to 1 more
		p.vstack = p.vstack[:len(p.vstack)+1]
	}

	// get the last args set
	m := p.vstack[len(p.vstack)-1]
	if m != nil && len(m) == 0 {
		// empty map, all good
		return
	}

	m = make(map[string]any)
	p.vstack[len(p.vstack)-1] = m
}

// pop a variable set from the vstack.
func (p *parser) popV() {
	// if the map is not empty, clear it
	m := p.vstack[len(p.vstack)-1]
	if len(m) > 0 {
		// GC that map
		p.vstack[len(p.vstack)-1] = nil
	}
	p.vstack = p.vstack[:len(p.vstack)-1]
}

// push a recovery expression with its labels to the recoveryStack
func (p *parser) pushRecovery(labels []string, expr any) {
	if cap(p.recoveryStack) == len(p.recoveryStack) {
		// create new empty slot in the stack
		p.recoveryStack = append(p.recoveryStack, nil)
	} else {
		// slice to 1 more
		p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)+1]
	}

	m := make(map[string]any, len(labels))
	for _, fl := range labels {
		m[fl] = expr
	}
	p.recoveryStack[len(p.recoveryStack)-1] = m
}

// pop a recovery expression from the recoveryStack
func (p *parser) popRecovery() {
	// GC that map
	p.recoveryStack[len(p.recoveryStack)-1] = nil

	p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)-1]
}

func (p *parser) print(prefix, s string) string {
	if !p.debug {
		return s
	}

	fmt.Printf("%s %d:%d:%d: %s [%#U]\n",
		prefix, p.pt.line, p.pt.col, p.pt.offset, s, p.pt.rn)
	return s
}

func (p *parser) printIndent(mark string, s string) string {
	return p.print(strings.Repeat(" ", p.depth)+mark, s)
}

func (p *parser) in(s string) string {
	res := p.printIndent(">", s)
	p.depth++
	return res
}

func (p *parser) out(s string) string {
	p.depth--
	return p.printIndent("<", s)
}

func (p *parser) addErr(err error) {
	p.addErrAt(err, p.pt.position, []string{})
}

func (p *parser) addErrAt(err error, pos position, expected []string) {
	var buf bytes.Buffer
	if p.filename != "" {
		buf.WriteString(p.filename)
	}
	if buf.Len() > 0 {
		buf.WriteString(":")
	}
	buf.WriteString(fmt.Sprintf("%d:%d (%d)", pos.line, pos.col, pos.offset))
	if len(p.rstack) > 0 {
		if buf.Len() > 0 {
			buf.WriteString(": ")
		}
		rule := p.rstack[len(p.rstack)-1]
		if rule.displayName != "" {
			buf.WriteString("rule " + rule.displayName)
		} else {
			buf.WriteString("rule " + rule.name)
		}
	}
	pe := &parserError{Inner: err, pos: pos, prefix: buf.String(), expected: expected}
	p.errs.add(pe)
}

func (p *parser) failAt(fail bool, pos position, want string) {
	// process fail if parsing fails and not inverted or parsing succeeds and invert is set
	if fail == p.maxFailInvertExpected {
		if pos.offset < p.maxFailPos.offset {
			return
		}

		if pos.offset > p.maxFailPos.offset {
			p.maxFailPos = pos
			p.maxFailExpected = p.maxFailExpected[:0]
		}

		if p.maxFailInvertExpected {
			want = "!" + want
		}
		p.maxFailExpected = append(p.maxFailExpected, want)
	}
}

// read advances the parser to the next rune.
func (p *parser) read() {
	p.pt.offset += p.pt.w
	rn, n := utf8.DecodeRune(p.data[p.pt.offset:])
	p.pt.rn = rn
	p.pt.w = n
	p.pt.col++
	if rn == '\n' {
		p.pt.line++
		p.pt.col = 0
	}

	if rn == utf8.RuneError && n == 1 { // see utf8.DecodeRune
		if !p.allowInvalidUTF8 {
			p.addErr(errInvalidEncoding)
		}
	}
}

// restore parser position to the savepoint pt.
func (p *parser) restore(pt savepoint) {
	if p.debug {
		defer p.out(p.in("restore"))
	}
	if pt.offset == p.pt.offset {
		return
	}
	p.pt = pt
}

// Cloner is implemented by any value that has a Clone method, which returns a
// copy of the value. This is mainly used for types which are not passed by
// value (e.g map, slice, chan) or structs that contain such types.
//
// This is used in conjunction with the global state feature to create proper
// copies of the state to allow the parser to properly restore the state in
// the case of backtracking.
type Cloner interface {
	Clone() any
}

var statePool = &sync.Pool{
	New: func() any { return make(storeDict) },
}

func (sd storeDict) Discard() {
	for k := range sd {
		delete(sd, k)
	}
	statePool.Put(sd)
}

// clone and return parser current state.
func (p *parser) cloneState() storeDict {
	if p.debug {
		defer p.out(p.in("cloneState"))
	}

	state := statePool.Get().(storeDict)
	for k, v := range p.cur.state {
		if c, ok := v.(Cloner); ok {
			state[k] = c.Clone()
		} else {
			state[k] = v
		}
	}
	return state
}

// restore parser current state to the state storeDict.
// every restoreState should applied only one time for every cloned state
func (p *parser) restoreState(state storeDict) {
	if p.debug {
		defer p.out(p.in("restoreState"))
	}
	p.cur.state.Discard()
	p.cur.state = state
}

// get the slice of bytes from the savepoint start to the current position.
func (p *parser) sliceFrom(start savepoint) []byte {
	return p.data[start.position.offset:p.pt.position.offset]
}

func (p *parser) getMemoized(node any) (resultTuple, bool) {
	if len(p.memo) == 0 {
		return resultTuple{}, false
	}
	m := p.memo[p.pt.offset]
	if len(m) == 0 {
		return resultTuple{}, false
	}
	res, ok := m[node]
	return res, ok
}

func (p *parser) setMemoized(pt savepoint, node any, tuple resultTuple) {
	if p.memo == nil {
		p.memo = make(map[int]map[any]resultTuple)
	}
	m := p.memo[pt.offset]
	if m == nil {
		m = make(map[any]resultTuple)
		p.memo[pt.offset] = m
	}
	m[node] = tuple
}

func (p *parser) buildRulesTable(g *grammar) {
	p.rules = make(map[string]*rule, len(g.rules))
	for _, r := range g.rules {
		p.rules[r.name] = r
	}
}

func (p *parser) parse(g *grammar) (val any, err error) {
	if len(g.rules) == 0 {
		p.addErr(errNoRule)
		return nil, p.errs.err()
	}

	// TODO : not super critical but this could be generated
	p.buildRulesTable(g)

	if p.recover {
		// panic can be used in action code to stop parsing immediately
		// and return the panic as an error.
		defer func() {
			if e := recover(); e != nil {
				if p.debug {
					defer p.out(p.in("panic handler"))
				}
				val = nil
				switch e := e.(type) {
				case error:
					p.addErr(e)
				default:
					p.addErr(fmt.Errorf("%v", e))
				}
				err = p.errs.err()
			}
		}()
	}

	startRule, ok := p.rules[p.entrypoint]
	if !ok {
		p.addErr(errInvalidEntrypoint)
		return nil, p.errs.err()
	}

	p.read() // advance to first rune
	val, ok = p.parseRuleWrap(startRule)
	if !ok {
		if len(*p.errs) == 0 {
			// If parsing fails, but no errors have been recorded, the expected values
			// for the farthest parser position are returned as error.
			maxFailExpectedMap := make(map[string]struct{}, len(p.maxFailExpected))
			for _, v := range p.maxFailExpected {
				maxFailExpectedMap[v] = struct{}{}
			}
			expected := make([]string, 0, len(maxFailExpectedMap))
			eof := false
			if _, ok := maxFailExpectedMap["!."]; ok {
				delete(maxFailExpectedMap, "!.")
				eof = true
			}
			for k := range maxFailExpectedMap {
				expected = append(expected, k)
			}
			sort.Strings(expected)
			if eof {
				expected = append(expected, "EOF")
			}
			p.addErrAt(errors.New("no match found, expected: "+listJoin(expected, ", ", "or")), p.maxFailPos, expected)
		}

		return nil, p.errs.err()
	}
	return val, p.errs.err()
}

func listJoin(list []string, sep string, lastSep string) string {
	switch len(list) {
	case 0:
		return ""
	case 1:
		return list[0]
	default:
		return strings.Join(list[:len(list)-1], sep) + " " + lastSep + " " + list[len(list)-1]
	}
}

func (p *parser) parseRuleMemoize(rule *rule) (any, bool) {
	res, ok := p.getMemoized(rule)
	if ok {
		p.restore(res.end)
		return res.v, res.b
	}

	startMark := p.pt
	val, ok := p.parseRule(rule)
	p.setMemoized(startMark, rule, resultTuple{val, ok, p.pt})

	return val, ok
}

func (p *parser) parseRuleWrap(rule *rule) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRule " + rule.name))
	}
	var (
		val       any
		ok        bool
		startMark = p.pt
	)

	if p.memoize {
		val, ok = p.parseRuleMemoize(rule)
	} else {
		val, ok = p.parseRule(rule)
	}

	if ok && p.debug {
		p.printIndent("MATCH", string(p.sliceFrom(startMark)))
	}
	return val, ok
}

func (p *parser) parseRule(rule *rule) (any, bool) {
	p.rstack = append(p.rstack, rule)
	p.pushV()
	val, ok := p.parseExprWrap(rule.expr)
	p.popV()
	p.rstack = p.rstack[:len(p.rstack)-1]
	return val, ok
}

func (p *parser) parseExprWrap(expr any) (any, bool) {
	var pt savepoint

	if p.memoize {
		res, ok := p.getMemoized(expr)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
		pt = p.pt
	}

	val, ok := p.parseExpr(expr)

	if p.memoize {
		p.setMemoized(pt, expr, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseExpr(expr any) (any, bool) {
	p.ExprCnt++
	if p.ExprCnt > p.maxExprCnt {
		panic(errMaxExprCnt)
	}

	var val any
	var ok bool
	switch expr := expr.(type) {
	case *actionExpr:
		val, ok = p.parseActionExpr(expr)
	case *andCodeExpr:
		val, ok = p.parseAndCodeExpr(expr)
	case *andExpr:
		val, ok = p.parseAndExpr(expr)
	case *anyMatcher:
		val, ok = p.parseAnyMatcher(expr)
	case *charClassMatcher:
		val, ok = p.parseCharClassMatcher(expr)
	case *choiceExpr:
		val, ok = p.parseChoiceExpr(expr)
	case *labeledExpr:
		val, ok = p.parseLabeledExpr(expr)
	case *litMatcher:
		val, ok = p.parseLitMatcher(expr)
	case *notCodeExpr:
		val, ok = p.parseNotCodeExpr(expr)
	case *notExpr:
		val, ok = p.parseNotExpr(expr)
	case *oneOrMoreExpr:
		val, ok = p.parseOneOrMoreExpr(expr)
	case *recoveryExpr:
		val, ok = p.parseRecoveryExpr(expr)
	case *ruleRefExpr:
		val, ok = p.parseRuleRefExpr(expr)
	case *seqExpr:
		val, ok = p.parseSeqExpr(expr)
	case *stateCodeExpr:
		val, ok = p.parseStateCodeExpr(expr)
	case *throwExpr:
		val, ok = p.parseThrowExpr(expr)
	case *zeroOrMoreExpr:
		val, ok = p.parseZeroOrMoreExpr(expr)
	case *zeroOrOneExpr:
		val, ok = p.parseZeroOrOneExpr(expr)
	default:
		panic(fmt.Sprintf("unknown expression type %T", expr))
	}
	return val, ok
}

func (p *parser) parseActionExpr(act *actionExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseActionExpr"))
	}

	start := p.pt
	val, ok := p.parseExprWrap(act.expr)
	if ok {
		p.cur.pos = start.position
		p.cur.text = p.sliceFrom(start)
		state := p.cloneState()
		actVal, err := act.run(p)
		if err != nil {
			p.addErrAt(err, start.position, []string{})
		}
		p.restoreState(state)

		val = actVal
	}
	if ok && p.debug {
		p.printIndent("MATCH", string(p.sliceFrom(start)))
	}
	return val, ok
}

func (p *parser) parseAndCodeExpr(and *andCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAndCodeExpr"))
	}

	state := p.cloneState()

	ok, err := and.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, ok
}

func (p *parser) parseAndExpr(and *andExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAndExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	_, ok := p.parseExprWrap(and.expr)
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, ok
}

func (p *parser) parseAnyMatcher(any *anyMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAnyMatcher"))
	}

	if p.pt.rn == utf8.RuneError && p.pt.w == 0 {
		// EOF - see utf8.DecodeRune
		p.failAt(false, p.pt.position, ".")
		return nil, false
	}
	start := p.pt
	p.read()
	p.failAt(true, start.position, ".")
	return p.sliceFrom(start), true
}

func (p *parser) parseCharClassMatcher(chr *charClassMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseCharClassMatcher"))
	}

	cur := p.pt.rn
	start := p.pt

	// can't match EOF
	if cur == utf8.RuneError && p.pt.w == 0 { // see utf8.DecodeRune
		p.failAt(false, start.position, chr.val)
		return nil, false
	}

	if chr.ignoreCase {
		cur = unicode.ToLower(cur)
	}

	// try to match in the list of available chars
	for _, rn := range chr.chars {
		if rn == cur {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of ranges
	for i := 0; i < len(chr.ranges); i += 2 {
		if cur >= chr.ranges[i] && cur <= chr.ranges[i+1] {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of Unicode classes
	for _, cl := range chr.classes {
		if unicode.Is(cl, cur) {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	if chr.inverted {
		p.read()
		p.failAt(true, start.position, chr.val)
		return p.sliceFrom(start), true
	}
	p.failAt(false, start.position, chr.val)
	return nil, false
}

func (p *parser) incChoiceAltCnt(ch *choiceExpr, altI int) {
	choiceIdent := fmt.Sprintf("%s %d:%d", p.rstack[len(p.rstack)-1].name, ch.pos.line, ch.pos.col)
	m := p.ChoiceAltCnt[choiceIdent]
	if m == nil {
		m = make(map[string]int)
		p.ChoiceAltCnt[choiceIdent] = m
	}
	// We increment altI by 1, so the keys do not start at 0
	alt := strconv.Itoa(altI + 1)
	if altI == choiceNoMatch {
		alt = p.choiceNoMatch
	}
	m[alt]++
}

func (p *parser) parseChoiceExpr(ch *choiceExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseChoiceExpr"))
	}

	for altI, alt := range ch.alternatives {
		// dummy assignment to prevent compile error if optimized
		_ = altI

		state := p.cloneState()

		p.pushV()
		val, ok := p.parseExprWrap(alt)
		p.popV()
		if ok {
			p.incChoiceAltCnt(ch, altI)
			return val, ok
		}
		p.restoreState(state)
	}
	p.incChoiceAltCnt(ch, choiceNoMatch)
	return nil, false
}

func (p *parser) parseLabeledExpr(lab *labeledExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseLabeledExpr"))
	}

	p.pushV()
	val, ok := p.parseExprWrap(lab.expr)
	p.popV()
	if ok && lab.label != "" {
		m := p.vstack[len(p.vstack)-1]
		m[lab.label] = val
	}
	return val, ok
}

func (p *parser) parseLitMatcher(lit *litMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseLitMatcher"))
	}

	start := p.pt
	for _, want := range lit.val {
		cur := p.pt.rn
		if lit.ignoreCase {
			cur = unicode.ToLower(cur)
		}
		if cur != want {
			p.failAt(false, start.position, lit.want)
			p.restore(start)
			return nil, false
		}
		p.read()
	}
	p.failAt(true, start.position, lit.want)
	return p.sliceFrom(start), true
}

func (p *parser) parseNotCodeExpr(not *notCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseNotCodeExpr"))
	}

	state := p.cloneState()

	ok, err := not.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, !ok
}

func (p *parser) parseNotExpr(not *notExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseNotExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	_, ok := p.parseExprWrap(not.expr)
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, !ok
}

func (p *parser) parseOneOrMoreExpr(expr *oneOrMoreExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseOneOrMoreExpr"))
	}

	var vals []any

	for {
		p.pushV()
		val, ok := p.parseExprWrap(expr.expr)
		p.popV()
		if !ok {
			if len(vals) == 0 {
				// did not match once, no match
				return nil, false
			}
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseRecoveryExpr(recover *recoveryExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRecoveryExpr (" + strings.Join(recover.failureLabel, ",") + ")"))
	}

	p.pushRecovery(recover.failureLabel, recover.recoverExpr)
	val, ok := p.parseExprWrap(recover.expr)
	p.popRecovery()

	return val, ok
}

func (p *parser) parseRuleRefExpr(ref *ruleRefExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRuleRefExpr " + ref.name))
	}

	if ref.name == "" {
		panic(fmt.Sprintf("%s: invalid rule: missing name", ref.pos))
	}

	rule := p.rules[ref.name]
	if rule == nil {
		p.addErr(fmt.Errorf("undefined rule: %s", ref.name))
		return nil, false
	}
	return p.parseRuleWrap(rule)
}

func (p *parser) parseSeqExpr(seq *seqExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseSeqExpr"))
	}

	vals := make([]any, 0, len(seq.exprs))

	pt := p.pt
	state := p.cloneState()
	for _, expr := range seq.exprs {
		val, ok := p.parseExprWrap(expr)
		if !ok {
			p.restoreState(state)
			p.restore(pt)
			return nil, false
		}
		vals = append(vals, val)
	}
	return vals, true
}

func (p *parser) parseStateCodeExpr(state *stateCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseStateCodeExpr"))
	}

	err := state.run(p)
	if err != nil {
		p.addErr(err)
	}
	return nil, true
}

func (p *parser) parseThrowExpr(expr *throwExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseThrowExpr"))
	}

	for i := len(p.recoveryStack) - 1; i >= 0; i-- {
		if recoverExpr, ok := p.recoveryStack[i][expr.label]; ok {
			if val, ok := p.parseExprWrap(recoverExpr); ok {
				return val, ok
			}
		}
	}

	return nil, false
}

func (p *parser) parseZeroOrMoreExpr(expr *zeroOrMoreExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrMoreExpr"))
	}

	var vals []any

	for {
		p.pushV()
		val, ok := p.parseExprWrap(expr.expr)
		p.popV()
		if !ok {
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseZeroOrOneExpr(expr *zeroOrOneExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrOneExpr"))
	}

	p.pushV()
	val, _ := p.parseExprWrap(expr.expr)
	p.popV()
	// whether it matched or not, consider it a match
	return val, true
}
