// Generated by unobin generate golibrary --from tf.

package demo

// ProviderConfig is the operator-facing body for configurations such as
// demo { ... } or name: demo { ... }.
type ProviderConfig struct {
	Region string
}
