// Generated by unobin generate golibrary --from tf.

package demo

import (
	"example.com/demo/data"
	"example.com/demo/resources"

	"github.com/cloudboss/unobin/pkg/runtime"
	"github.com/cloudboss/unobin/pkg/sdk/cfg"
)

func Library() *runtime.Library {
	return &runtime.Library{
		Name:        "demo",
		LibraryPath: "example.com/demo",
		Description: "Generated demo library",
		Configuration: &cfg.ConfigurationType[any]{
			Description: "demo provider configuration.",
			New:         func() any { return &ProviderConfig{} },
		},
		Resources: map[string]runtime.ResourceRegistration{
			"bucket": runtime.MakeResource[resources.Bucket, *resources.BucketOutput, any](),
		},
		DataSources: map[string]runtime.DataSourceRegistration{
			"image":   runtime.MakeDataSource[data.Image, *data.ImageOutput, any](),
			"network": runtime.MakeDataSource[data.Network, *data.NetworkOutput, any](),
		},
	}
}
