package codegen

import (
	"go/parser"
	"go/token"
	"strings"
	"testing"

	"github.com/stretchr/testify/require"
)

func TestGenerateValidGo(t *testing.T) {
	out, err := Generate(Input{
		Body:      "actions: { core: { command: { hi: { argv: ['echo', 'world'] } } } }\n",
		StackName: "demo",
		GoImports: map[string]string{
			"core": "github.com/cloudboss/unobin/pkg/libraries/core",
		},
	})
	require.NoError(t, err)

	fset := token.NewFileSet()
	_, err = parser.ParseFile(fset, "main.go", out, parser.AllErrors)
	require.NoError(t, err, "generated source should parse:\n%s", string(out))
}

func TestGenerateEmbedsStackName(t *testing.T) {
	out, err := Generate(Input{
		Body:      "description: 'x'\n",
		StackName: "my-stack",
		GoImports: map[string]string{
			"core": "github.com/cloudboss/unobin/pkg/libraries/core",
		},
	})
	require.NoError(t, err)

	s := string(out)
	require.Contains(t, s, `stackName        = "my-stack"`)
}

func TestGenerateDeclaresStampVars(t *testing.T) {
	out, err := Generate(Input{
		Body:      "description: 'x'\n",
		StackName: "my-stack",
		GoImports: map[string]string{
			"core": "github.com/cloudboss/unobin/pkg/libraries/core",
		},
	})
	require.NoError(t, err)

	s := string(out)
	require.Contains(t, s, "var (\n\tstackVersion    string\n\tcontentRevision string\n)")
}

func TestGenerateEmbedsBodyVerbatim(t *testing.T) {
	src := "actions: { core: { command: { x: { argv: ['echo', \"with quotes\"] } } } }"
	out, err := Generate(Input{
		Body:      src,
		StackName: "x",
		GoImports: map[string]string{"core": "github.com/cloudboss/unobin/pkg/libraries/core"},
	})
	require.NoError(t, err)

	require.Contains(t, string(out), `"actions: { core: { command: { x: { argv: ['echo', \"with quotes\"] } } } }"`)
}

func TestGenerateOrdersImports(t *testing.T) {
	out, err := Generate(Input{
		Body:      "description: 'x'\n",
		StackName: "x",
		GoImports: map[string]string{
			"net":  "github.com/me/libraries/network",
			"aws":  "github.com/cloudboss/unobin-libraries/aws",
			"core": "github.com/cloudboss/unobin/pkg/libraries/core",
		},
	})
	require.NoError(t, err)

	s := string(out)
	awsAt := strings.Index(s, `"github.com/cloudboss/unobin-libraries/aws"`)
	coreAt := strings.Index(s, `"github.com/cloudboss/unobin/pkg/libraries/core"`)
	netAt := strings.Index(s, `"github.com/me/libraries/network"`)
	require.True(t, awsAt > 0 && coreAt > 0 && netAt > 0,
		"all imports should appear in source")
	require.Less(t, awsAt, coreAt, "aws should appear before core")
	require.Less(t, coreAt, netAt, "core should appear before net")
}

func TestGenerateRequiresStackName(t *testing.T) {
	_, err := Generate(Input{
		Body:      "description: 'x'",
		GoImports: map[string]string{"core": "github.com/cloudboss/unobin/pkg/libraries/core"},
	})
	require.Error(t, err)
	require.Contains(t, err.Error(), "StackName")
}

func TestGenerateImportsAndCallsUBLibraries(t *testing.T) {
	out, err := Generate(Input{
		Body:      "description: 'x'",
		StackName: "demo",
		GoImports: map[string]string{
			"core": "github.com/cloudboss/unobin/pkg/libraries/core",
		},
		UBImports: map[string]string{
			"net":     "demo/internal/net",
			"cluster": "demo/internal/cluster",
		},
	})
	require.NoError(t, err)

	want := `// Code generated by unobin. DO NOT EDIT.
package main

import (
	lib_cluster "demo/internal/cluster"
	lib_net "demo/internal/net"
	lib_core "github.com/cloudboss/unobin/pkg/libraries/core"
	"github.com/cloudboss/unobin/pkg/runner"
	"github.com/cloudboss/unobin/pkg/runtime"
)

const (
	stackBody        = "description: 'x'"
	stackLibraryPath = ""
	stackName        = "demo"
)

// Stamped at link time via -ldflags.
var (
	stackVersion    string
	contentRevision string
)

func main() {
	runner.Run(runner.Info{
		StackName:       stackName,
		StackVersion:    stackVersion,
		ContentRevision: contentRevision,
		StackBody:       stackBody,
		LibraryPath:     stackLibraryPath,
		Libraries: map[string]*runtime.Library{
			"core":    lib_core.Library(),
			"cluster": lib_cluster.Library(),
			"net":     lib_net.Library(),
		},
	})
}
`
	require.Equal(t, want, string(out))
}

func TestGenerateBuildsLibrariesMap(t *testing.T) {
	out, err := Generate(Input{
		Body:      "description: 'x'",
		StackName: "x",
		GoImports: map[string]string{
			"core": "github.com/cloudboss/unobin/pkg/libraries/core",
			"aws":  "github.com/cloudboss/unobin-libraries/aws",
		},
	})
	require.NoError(t, err)

	s := string(out)
	require.Contains(t, s, `"aws":  lib_aws.Library(),`)
	require.Contains(t, s, `"core": lib_core.Library(),`)
}
