package codegen

import (
	"bytes"
	"fmt"
	"go/format"
	"sort"
	"strconv"
	"text/template"
)

// Input bundles everything codegen needs to produce a stack binary's
// `main.go`. Source is the literal stack source the binary embeds and
// parses on each invocation. StackName, Version, and Commit identify
// the binary back to the operator's `config.ub`. GoImports maps each
// module alias the source uses to the Go import path that supplies it
// (e.g., "core" -> "github.com/cloudboss/unobin/pkg/modules/core").
type Input struct {
	Source    string
	StackName string
	Version   string
	Commit    string
	GoImports map[string]string
}

// Generate produces the formatted Go source for the stack binary's
// main.go. The result is the bytes a caller writes to disk and feeds
// through `go build`.
func Generate(in Input) ([]byte, error) {
	if in.StackName == "" {
		return nil, fmt.Errorf("codegen: StackName is required")
	}
	aliases := sortedKeys(in.GoImports)
	data := struct {
		Source    string
		StackName string
		Version   string
		Commit    string
		Aliases   []string
		Imports   map[string]string
	}{
		Source:    in.Source,
		StackName: in.StackName,
		Version:   in.Version,
		Commit:    in.Commit,
		Aliases:   aliases,
		Imports:   in.GoImports,
	}

	var buf bytes.Buffer
	if err := mainTemplate.Execute(&buf, data); err != nil {
		return nil, fmt.Errorf("codegen: %w", err)
	}
	out, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("codegen: format generated source: %w", err)
	}
	return out, nil
}

func sortedKeys(m map[string]string) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

// quote renders a string as a Go double quoted literal. Used by the
// template to embed the stack source verbatim.
func quote(s string) string {
	return strconv.Quote(s)
}

var mainTemplate = template.Must(template.New("main.go").Funcs(template.FuncMap{
	"quote": quote,
}).Parse(`// Code generated by unobin. DO NOT EDIT.
package main

import (
	"context"
	"fmt"
	"os"

	"github.com/cloudboss/unobin/pkg/lang"
	"github.com/cloudboss/unobin/pkg/runtime"
	"github.com/cloudboss/unobin/pkg/state"
{{range .Aliases}}	mod_{{.}} {{quote (index $.Imports .)}}
{{end -}}
)

const (
	stackSource  = {{quote .Source}}
	stackName    = {{quote .StackName}}
	stackVersion = {{quote .Version}}
	stackCommit  = {{quote .Commit}}
)

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run() error {
	f, err := lang.ParseSource("stack.ub", []byte(stackSource))
	if err != nil {
		return err
	}
	if errs := lang.ValidateFile(f); errs.Len() > 0 {
		return errs.Err()
	}

	store, err := state.NewLocalStore(".unobin/state", stackName, "default", state.NoopEncrypter{})
	if err != nil {
		return err
	}

	exec := &runtime.Executor{
		DAG: runtime.BuildDAG(f),
		Modules: map[string]*runtime.Module{
{{range .Aliases}}			{{quote .}}: mod_{{.}}.Module(),
{{end}}		},
		Store: store,
		Stack: state.StackInfo{Name: stackName, Version: stackVersion, Commit: stackCommit},
	}

	res, err := exec.Run(context.Background())
	if err != nil {
		return err
	}
	for k, v := range res.Outputs {
		fmt.Printf("%s = %v\n", k, v)
	}
	return nil
}
`))
