package codegen

import (
	"bytes"
	"fmt"
	"go/format"
	"sort"
	"strconv"
	"text/template"
)

// Input bundles everything codegen needs to produce a stack binary's
// `main.go`. Body is the literal stack source the binary embeds and
// parses on each invocation. ModulePath is the binary's module-path
// identity, the same shape Go modules use; the operator's `config.ub`
// asserts the same value under `stack.module-path` and plan, refresh,
// and validate refuse on mismatch. An empty ModulePath disables that
// identity check. StackName, Version, and ContentRevision identify the binary
// back to its `config.ub`. GoImports maps each Go-module alias the
// source uses to the Go import path that supplies it (e.g.,
// `"core" -> "github.com/cloudboss/unobin/pkg/modules/core"`).
// UBImports maps each UB-module alias to the local Go import path of
// the package that compile generated for it (typically
// `<stack-name>/internal/<alias>`).
type Input struct {
	Body            string
	ModulePath      string
	StackName       string
	Version         string
	ContentRevision string
	GoImports       map[string]string
	UBImports       map[string]string
}

// Generate produces the formatted Go source for the stack binary's
// main.go. The result is the bytes a caller writes to disk and feeds
// through `go build`.
func Generate(in Input) ([]byte, error) {
	if in.StackName == "" {
		return nil, fmt.Errorf("codegen: StackName is required")
	}
	aliases := sortedKeys(in.GoImports)
	ubAliases := sortedKeys(in.UBImports)
	data := struct {
		Body            string
		ModulePath      string
		StackName       string
		Version         string
		ContentRevision string
		Aliases         []string
		Imports         map[string]string
		UBAliases       []string
		UBImports       map[string]string
	}{
		Body:            in.Body,
		ModulePath:      in.ModulePath,
		StackName:       in.StackName,
		Version:         in.Version,
		ContentRevision: in.ContentRevision,
		Aliases:         aliases,
		Imports:         in.GoImports,
		UBAliases:       ubAliases,
		UBImports:       in.UBImports,
	}

	var buf bytes.Buffer
	if err := mainTemplate.Execute(&buf, data); err != nil {
		return nil, fmt.Errorf("codegen: %w", err)
	}
	out, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("codegen: format generated source: %w", err)
	}
	return out, nil
}

func sortedKeys(m map[string]string) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

// quote renders a string as a Go double quoted literal. Used by the
// template to embed the stack source verbatim.
func quote(s string) string {
	return strconv.Quote(s)
}

var mainTemplate = template.Must(template.New("main.go").Funcs(template.FuncMap{
	"quote": quote,
}).Parse(`// Code generated by unobin. DO NOT EDIT.
package main

import (
	"github.com/cloudboss/unobin/pkg/runner"
	"github.com/cloudboss/unobin/pkg/runtime"
{{range .Aliases}}	mod_{{.}} {{quote (index $.Imports .)}}
{{end}}{{range .UBAliases}}	mod_{{.}} {{quote (index $.UBImports .)}}
{{end -}}
)

const (
	stackBody       = {{quote .Body}}
	stackModulePath = {{quote .ModulePath}}
	stackName       = {{quote .StackName}}
	stackVersion    = {{quote .Version}}
	contentRevision = {{quote .ContentRevision}}
)

func main() {
	runner.Run(runner.Info{
		StackName:       stackName,
		StackVersion:    stackVersion,
		ContentRevision: contentRevision,
		StackBody:       stackBody,
		ModulePath:      stackModulePath,
		Modules: map[string]*runtime.Module{
{{range .Aliases}}			{{quote .}}: mod_{{.}}.Module(),
{{end}}{{range .UBAliases}}			{{quote .}}: mod_{{.}}.Module(),
{{end}}		},
	})
}
`))
