// Code generated by unobin. DO NOT EDIT.
package main

import (
	lib_self "demo-factory/internal/self"
	"github.com/cloudboss/unobin/pkg/runner"
	"github.com/cloudboss/unobin/pkg/runtime"
)

const (
	factoryBody        = "factory: {\n  imports: { self: '.' }\n  data-sources: {\n    message: self.message {}\n  }\n  outputs: { text: { value: data-source.message.text } }\n}\n"
	factoryLibraryPath = ""
	factoryName        = "demo-factory"
)

// Stamped at link time via -ldflags.
var (
	factoryVersion  string
	contentRevision string
	unobinVersion   string
)

func main() {
	runner.Run(runner.Info{
		FactoryName:     factoryName,
		FactoryVersion:  factoryVersion,
		ContentRevision: contentRevision,
		FactoryBody:     factoryBody,
		LibraryPath:     factoryLibraryPath,
		Libraries: map[string]*runtime.Library{
			"self": lib_self.Library(),
		},
		UnobinVersion: unobinVersion,
	})
}
