// Code generated by unobin. DO NOT EDIT.
package self

import (
	"github.com/cloudboss/unobin/pkg/lang"
	"github.com/cloudboss/unobin/pkg/lang/syntax"
	"github.com/cloudboss/unobin/pkg/runtime"
)

func Library() *runtime.Library {
	return &runtime.Library{
		Name: "self",
		DataComposites: map[string]*runtime.CompositeType{
			"message": {
				Name:       "message",
				Kind:       runtime.NodeData,
				SyntaxBody: &syntax.FactoryBody{Outputs: []syntax.OutputDecl{{Name: syntax.Ident{Name: "text"}, Body: &lang.ObjectLit{Fields: []*lang.Field{{Key: lang.FieldKey{Kind: lang.FieldIdent, Name: "value"}, Value: &lang.StringLit{Value: "hi"}}}}}}},
			},
		},
	}
}
