package compiler

// Code generated by peg grammar.peg DO NOT EDIT.

import (
	"fmt"
	"io"
	"os"
	"sort"
	"strconv"
	"strings"
)

const endSymbol rune = 1114112

/* The rule types inferred from the grammar are below. */
type pegRule uint8

const (
	ruleUnknown pegRule = iota
	ruleentry
	ruleident
	ruleident_chars
	ruleident_char
	rulecomment
	rulespace
	rulenot_newline
	rulenewline
	ruleall_space
	rulealpha
	ruledigit
	rulesentence_char
	rulesentence
	rulestatement
	rulepair
	rulevalue
	ruleindex_expr
	ruleindex_expr_tail
	rulearray
	rulebool_expr
	ruleitem_delim
	rulefun_expr
	rulemath_expr
	rulenumber
	ruleint
	rulefloat
	ruleobject
	rulestring
	rulestring_body
	ruleblock
	rulesimple_block
	ruleblock_description
	rulecompound_block
	rulerescue_clause
	rulealways_clause
	ruleend
	rulePAIR_DELIM
	ruleDOT
	ruleSTRING_DELIM
	ruleCOMMENT_START
	ruleMINUS
	ruleINDEX_OPEN
	ruleINDEX_CLOSE
	ruleARRAY_OPEN
	ruleARRAY_CLOSE
	ruleGROUP_OPEN
	ruleGROUP_CLOSE
	ruleOBJECT_OPEN
	ruleOBJECT_CLOSE
	ruleBLOCK
	ruleRESCUE
	ruleALWAYS
	ruleTRUE
	ruleFALSE
	ruleEQ
	ruleLT
	ruleGT
	ruleLTE
	ruleGTE
	ruleAND
	ruleOR
)

var rul3s = [...]string{
	"Unknown",
	"entry",
	"ident",
	"ident_chars",
	"ident_char",
	"comment",
	"space",
	"not_newline",
	"newline",
	"all_space",
	"alpha",
	"digit",
	"sentence_char",
	"sentence",
	"statement",
	"pair",
	"value",
	"index_expr",
	"index_expr_tail",
	"array",
	"bool_expr",
	"item_delim",
	"fun_expr",
	"math_expr",
	"number",
	"int",
	"float",
	"object",
	"string",
	"string_body",
	"block",
	"simple_block",
	"block_description",
	"compound_block",
	"rescue_clause",
	"always_clause",
	"end",
	"PAIR_DELIM",
	"DOT",
	"STRING_DELIM",
	"COMMENT_START",
	"MINUS",
	"INDEX_OPEN",
	"INDEX_CLOSE",
	"ARRAY_OPEN",
	"ARRAY_CLOSE",
	"GROUP_OPEN",
	"GROUP_CLOSE",
	"OBJECT_OPEN",
	"OBJECT_CLOSE",
	"BLOCK",
	"RESCUE",
	"ALWAYS",
	"TRUE",
	"FALSE",
	"EQ",
	"LT",
	"GT",
	"LTE",
	"GTE",
	"AND",
	"OR",
}

type token32 struct {
	pegRule
	begin, end uint32
}

func (t *token32) String() string {
	return fmt.Sprintf("\x1B[34m%v\x1B[m %v %v", rul3s[t.pegRule], t.begin, t.end)
}

type node32 struct {
	token32
	up, next *node32
}

func (node *node32) print(w io.Writer, pretty bool, buffer string) {
	var print func(node *node32, depth int)
	print = func(node *node32, depth int) {
		for node != nil {
			for c := 0; c < depth; c++ {
				fmt.Fprintf(w, " ")
			}
			rule := rul3s[node.pegRule]
			quote := strconv.Quote(string(([]rune(buffer)[node.begin:node.end])))
			if !pretty {
				fmt.Fprintf(w, "%v %v\n", rule, quote)
			} else {
				fmt.Fprintf(w, "\x1B[34m%v\x1B[m %v\n", rule, quote)
			}
			if node.up != nil {
				print(node.up, depth+1)
			}
			node = node.next
		}
	}
	print(node, 0)
}

func (node *node32) Print(w io.Writer, buffer string) {
	node.print(w, false, buffer)
}

func (node *node32) PrettyPrint(w io.Writer, buffer string) {
	node.print(w, true, buffer)
}

type tokens32 struct {
	tree []token32
}

func (t *tokens32) Trim(length uint32) {
	t.tree = t.tree[:length]
}

func (t *tokens32) Print() {
	for _, token := range t.tree {
		fmt.Println(token.String())
	}
}

func (t *tokens32) AST() *node32 {
	type element struct {
		node *node32
		down *element
	}
	tokens := t.Tokens()
	var stack *element
	for _, token := range tokens {
		if token.begin == token.end {
			continue
		}
		node := &node32{token32: token}
		for stack != nil && stack.node.begin >= token.begin && stack.node.end <= token.end {
			stack.node.next = node.up
			node.up = stack.node
			stack = stack.down
		}
		stack = &element{node: node, down: stack}
	}
	if stack != nil {
		return stack.node
	}
	return nil
}

func (t *tokens32) PrintSyntaxTree(buffer string) {
	t.AST().Print(os.Stdout, buffer)
}

func (t *tokens32) WriteSyntaxTree(w io.Writer, buffer string) {
	t.AST().Print(w, buffer)
}

func (t *tokens32) PrettyPrintSyntaxTree(buffer string) {
	t.AST().PrettyPrint(os.Stdout, buffer)
}

func (t *tokens32) Add(rule pegRule, begin, end, index uint32) {
	tree, i := t.tree, int(index)
	if i >= len(tree) {
		t.tree = append(tree, token32{pegRule: rule, begin: begin, end: end})
		return
	}
	tree[i] = token32{pegRule: rule, begin: begin, end: end}
}

func (t *tokens32) Tokens() []token32 {
	return t.tree
}

type Grammar struct {
	uast *UAST

	Buffer string
	buffer []rune
	rules  [62]func() bool
	parse  func(rule ...int) error
	reset  func()
	Pretty bool
	tokens32
}

func (p *Grammar) Parse(rule ...int) error {
	return p.parse(rule...)
}

func (p *Grammar) Reset() {
	p.reset()
}

type textPosition struct {
	line, symbol int
}

type textPositionMap map[int]textPosition

func translatePositions(buffer []rune, positions []int) textPositionMap {
	length, translations, j, line, symbol := len(positions), make(textPositionMap, len(positions)), 0, 1, 0
	sort.Ints(positions)

search:
	for i, c := range buffer {
		if c == '\n' {
			line, symbol = line+1, 0
		} else {
			symbol++
		}
		if i == positions[j] {
			translations[positions[j]] = textPosition{line, symbol}
			for j++; j < length; j++ {
				if i != positions[j] {
					continue search
				}
			}
			break search
		}
	}

	return translations
}

type parseError struct {
	p   *Grammar
	max token32
}

func (e *parseError) Error() string {
	tokens, err := []token32{e.max}, "\n"
	positions, p := make([]int, 2*len(tokens)), 0
	for _, token := range tokens {
		positions[p], p = int(token.begin), p+1
		positions[p], p = int(token.end), p+1
	}
	translations := translatePositions(e.p.buffer, positions)
	format := "parse error near %v (line %v symbol %v - line %v symbol %v):\n%v\n"
	if e.p.Pretty {
		format = "parse error near \x1B[34m%v\x1B[m (line %v symbol %v - line %v symbol %v):\n%v\n"
	}
	for _, token := range tokens {
		begin, end := int(token.begin), int(token.end)
		err += fmt.Sprintf(format,
			rul3s[token.pegRule],
			translations[begin].line, translations[begin].symbol,
			translations[end].line, translations[end].symbol,
			strconv.Quote(string(e.p.buffer[begin:end])))
	}

	return err
}

func (p *Grammar) PrintSyntaxTree() {
	if p.Pretty {
		p.tokens32.PrettyPrintSyntaxTree(p.Buffer)
	} else {
		p.tokens32.PrintSyntaxTree(p.Buffer)
	}
}

func (p *Grammar) WriteSyntaxTree(w io.Writer) {
	p.tokens32.WriteSyntaxTree(w, p.Buffer)
}

func (p *Grammar) SprintSyntaxTree() string {
	var bldr strings.Builder
	p.WriteSyntaxTree(&bldr)
	return bldr.String()
}

func Pretty(pretty bool) func(*Grammar) error {
	return func(p *Grammar) error {
		p.Pretty = pretty
		return nil
	}
}

func Size(size int) func(*Grammar) error {
	return func(p *Grammar) error {
		p.tokens32 = tokens32{tree: make([]token32, 0, size)}
		return nil
	}
}
func (p *Grammar) Init(options ...func(*Grammar) error) error {
	var (
		max                  token32
		position, tokenIndex uint32
		buffer               []rune
	)
	for _, option := range options {
		err := option(p)
		if err != nil {
			return err
		}
	}
	p.reset = func() {
		max = token32{}
		position, tokenIndex = 0, 0

		p.buffer = []rune(p.Buffer)
		if len(p.buffer) == 0 || p.buffer[len(p.buffer)-1] != endSymbol {
			p.buffer = append(p.buffer, endSymbol)
		}
		buffer = p.buffer
	}
	p.reset()

	_rules := p.rules
	tree := p.tokens32
	p.parse = func(rule ...int) error {
		r := 1
		if len(rule) > 0 {
			r = rule[0]
		}
		matches := p.rules[r]()
		p.tokens32 = tree
		if matches {
			p.Trim(tokenIndex)
			return nil
		}
		return &parseError{p, max}
	}

	add := func(rule pegRule, begin uint32) {
		tree.Add(rule, begin, position, tokenIndex)
		tokenIndex++
		if begin != position && position > max.end {
			max = token32{rule, begin, position}
		}
	}

	matchDot := func() bool {
		if buffer[position] != endSymbol {
			position++
			return true
		}
		return false
	}

	/*matchChar := func(c byte) bool {
		if buffer[position] == c {
			position++
			return true
		}
		return false
	}*/

	/*matchRange := func(lower byte, upper byte) bool {
		if c := buffer[position]; c >= lower && c <= upper {
			position++
			return true
		}
		return false
	}*/

	_rules = [...]func() bool{
		nil,
		/* 0 entry <- <(all_space* statement* end)> */
		func() bool {
			position0, tokenIndex0 := position, tokenIndex
			{
				position1 := position
			l2:
				{
					position3, tokenIndex3 := position, tokenIndex
					if !_rules[ruleall_space]() {
						goto l3
					}
					goto l2
				l3:
					position, tokenIndex = position3, tokenIndex3
				}
			l4:
				{
					position5, tokenIndex5 := position, tokenIndex
					if !_rules[rulestatement]() {
						goto l5
					}
					goto l4
				l5:
					position, tokenIndex = position5, tokenIndex5
				}
				if !_rules[ruleend]() {
					goto l0
				}
				add(ruleentry, position1)
			}
			return true
		l0:
			position, tokenIndex = position0, tokenIndex0
			return false
		},
		/* 1 ident <- <(ident_chars space*)> */
		func() bool {
			position6, tokenIndex6 := position, tokenIndex
			{
				position7 := position
				if !_rules[ruleident_chars]() {
					goto l6
				}
			l8:
				{
					position9, tokenIndex9 := position, tokenIndex
					if !_rules[rulespace]() {
						goto l9
					}
					goto l8
				l9:
					position, tokenIndex = position9, tokenIndex9
				}
				add(ruleident, position7)
			}
			return true
		l6:
			position, tokenIndex = position6, tokenIndex6
			return false
		},
		/* 2 ident_chars <- <(alpha ident_char*)> */
		func() bool {
			position10, tokenIndex10 := position, tokenIndex
			{
				position11 := position
				if !_rules[rulealpha]() {
					goto l10
				}
			l12:
				{
					position13, tokenIndex13 := position, tokenIndex
					if !_rules[ruleident_char]() {
						goto l13
					}
					goto l12
				l13:
					position, tokenIndex = position13, tokenIndex13
				}
				add(ruleident_chars, position11)
			}
			return true
		l10:
			position, tokenIndex = position10, tokenIndex10
			return false
		},
		/* 3 ident_char <- <(alpha / digit / MINUS)> */
		func() bool {
			position14, tokenIndex14 := position, tokenIndex
			{
				position15 := position
				{
					position16, tokenIndex16 := position, tokenIndex
					if !_rules[rulealpha]() {
						goto l17
					}
					goto l16
				l17:
					position, tokenIndex = position16, tokenIndex16
					if !_rules[ruledigit]() {
						goto l18
					}
					goto l16
				l18:
					position, tokenIndex = position16, tokenIndex16
					if !_rules[ruleMINUS]() {
						goto l14
					}
				}
			l16:
				add(ruleident_char, position15)
			}
			return true
		l14:
			position, tokenIndex = position14, tokenIndex14
			return false
		},
		/* 4 comment <- <(COMMENT_START not_newline* (newline / end))> */
		func() bool {
			position19, tokenIndex19 := position, tokenIndex
			{
				position20 := position
				if !_rules[ruleCOMMENT_START]() {
					goto l19
				}
			l21:
				{
					position22, tokenIndex22 := position, tokenIndex
					if !_rules[rulenot_newline]() {
						goto l22
					}
					goto l21
				l22:
					position, tokenIndex = position22, tokenIndex22
				}
				{
					position23, tokenIndex23 := position, tokenIndex
					if !_rules[rulenewline]() {
						goto l24
					}
					goto l23
				l24:
					position, tokenIndex = position23, tokenIndex23
					if !_rules[ruleend]() {
						goto l19
					}
				}
			l23:
				add(rulecomment, position20)
			}
			return true
		l19:
			position, tokenIndex = position19, tokenIndex19
			return false
		},
		/* 5 space <- <(' ' / '\t')> */
		func() bool {
			position25, tokenIndex25 := position, tokenIndex
			{
				position26 := position
				{
					position27, tokenIndex27 := position, tokenIndex
					if buffer[position] != rune(' ') {
						goto l28
					}
					position++
					goto l27
				l28:
					position, tokenIndex = position27, tokenIndex27
					if buffer[position] != rune('\t') {
						goto l25
					}
					position++
				}
			l27:
				add(rulespace, position26)
			}
			return true
		l25:
			position, tokenIndex = position25, tokenIndex25
			return false
		},
		/* 6 not_newline <- <(!('\r' / '\n') .)> */
		func() bool {
			position29, tokenIndex29 := position, tokenIndex
			{
				position30 := position
				{
					position31, tokenIndex31 := position, tokenIndex
					{
						position32, tokenIndex32 := position, tokenIndex
						if buffer[position] != rune('\r') {
							goto l33
						}
						position++
						goto l32
					l33:
						position, tokenIndex = position32, tokenIndex32
						if buffer[position] != rune('\n') {
							goto l31
						}
						position++
					}
				l32:
					goto l29
				l31:
					position, tokenIndex = position31, tokenIndex31
				}
				if !matchDot() {
					goto l29
				}
				add(rulenot_newline, position30)
			}
			return true
		l29:
			position, tokenIndex = position29, tokenIndex29
			return false
		},
		/* 7 newline <- <('\r' / '\n')> */
		func() bool {
			position34, tokenIndex34 := position, tokenIndex
			{
				position35 := position
				{
					position36, tokenIndex36 := position, tokenIndex
					if buffer[position] != rune('\r') {
						goto l37
					}
					position++
					goto l36
				l37:
					position, tokenIndex = position36, tokenIndex36
					if buffer[position] != rune('\n') {
						goto l34
					}
					position++
				}
			l36:
				add(rulenewline, position35)
			}
			return true
		l34:
			position, tokenIndex = position34, tokenIndex34
			return false
		},
		/* 8 all_space <- <(space / newline / comment)> */
		func() bool {
			position38, tokenIndex38 := position, tokenIndex
			{
				position39 := position
				{
					position40, tokenIndex40 := position, tokenIndex
					if !_rules[rulespace]() {
						goto l41
					}
					goto l40
				l41:
					position, tokenIndex = position40, tokenIndex40
					if !_rules[rulenewline]() {
						goto l42
					}
					goto l40
				l42:
					position, tokenIndex = position40, tokenIndex40
					if !_rules[rulecomment]() {
						goto l38
					}
				}
			l40:
				add(ruleall_space, position39)
			}
			return true
		l38:
			position, tokenIndex = position38, tokenIndex38
			return false
		},
		/* 9 alpha <- <([A-Z] / [a-z])> */
		func() bool {
			position43, tokenIndex43 := position, tokenIndex
			{
				position44 := position
				{
					position45, tokenIndex45 := position, tokenIndex
					if c := buffer[position]; c < rune('A') || c > rune('Z') {
						goto l46
					}
					position++
					goto l45
				l46:
					position, tokenIndex = position45, tokenIndex45
					if c := buffer[position]; c < rune('a') || c > rune('z') {
						goto l43
					}
					position++
				}
			l45:
				add(rulealpha, position44)
			}
			return true
		l43:
			position, tokenIndex = position43, tokenIndex43
			return false
		},
		/* 10 digit <- <[0-9]> */
		func() bool {
			position47, tokenIndex47 := position, tokenIndex
			{
				position48 := position
				if c := buffer[position]; c < rune('0') || c > rune('9') {
					goto l47
				}
				position++
				add(ruledigit, position48)
			}
			return true
		l47:
			position, tokenIndex = position47, tokenIndex47
			return false
		},
		/* 11 sentence_char <- <(!(INDEX_CLOSE / all_space) .)> */
		func() bool {
			position49, tokenIndex49 := position, tokenIndex
			{
				position50 := position
				{
					position51, tokenIndex51 := position, tokenIndex
					{
						position52, tokenIndex52 := position, tokenIndex
						if !_rules[ruleINDEX_CLOSE]() {
							goto l53
						}
						goto l52
					l53:
						position, tokenIndex = position52, tokenIndex52
						if !_rules[ruleall_space]() {
							goto l51
						}
					}
				l52:
					goto l49
				l51:
					position, tokenIndex = position51, tokenIndex51
				}
				if !matchDot() {
					goto l49
				}
				add(rulesentence_char, position50)
			}
			return true
		l49:
			position, tokenIndex = position49, tokenIndex49
			return false
		},
		/* 12 sentence <- <(sentence_char+ (space+ sentence_char+)*)> */
		func() bool {
			position54, tokenIndex54 := position, tokenIndex
			{
				position55 := position
				if !_rules[rulesentence_char]() {
					goto l54
				}
			l56:
				{
					position57, tokenIndex57 := position, tokenIndex
					if !_rules[rulesentence_char]() {
						goto l57
					}
					goto l56
				l57:
					position, tokenIndex = position57, tokenIndex57
				}
			l58:
				{
					position59, tokenIndex59 := position, tokenIndex
					if !_rules[rulespace]() {
						goto l59
					}
				l60:
					{
						position61, tokenIndex61 := position, tokenIndex
						if !_rules[rulespace]() {
							goto l61
						}
						goto l60
					l61:
						position, tokenIndex = position61, tokenIndex61
					}
					if !_rules[rulesentence_char]() {
						goto l59
					}
				l62:
					{
						position63, tokenIndex63 := position, tokenIndex
						if !_rules[rulesentence_char]() {
							goto l63
						}
						goto l62
					l63:
						position, tokenIndex = position63, tokenIndex63
					}
					goto l58
				l59:
					position, tokenIndex = position59, tokenIndex59
				}
				add(rulesentence, position55)
			}
			return true
		l54:
			position, tokenIndex = position54, tokenIndex54
			return false
		},
		/* 13 statement <- <(pair / block)> */
		func() bool {
			position64, tokenIndex64 := position, tokenIndex
			{
				position65 := position
				{
					position66, tokenIndex66 := position, tokenIndex
					if !_rules[rulepair]() {
						goto l67
					}
					goto l66
				l67:
					position, tokenIndex = position66, tokenIndex66
					if !_rules[ruleblock]() {
						goto l64
					}
				}
			l66:
				add(rulestatement, position65)
			}
			return true
		l64:
			position, tokenIndex = position64, tokenIndex64
			return false
		},
		/* 14 pair <- <((ident / string) PAIR_DELIM value all_space*)> */
		func() bool {
			position68, tokenIndex68 := position, tokenIndex
			{
				position69 := position
				{
					position70, tokenIndex70 := position, tokenIndex
					if !_rules[ruleident]() {
						goto l71
					}
					goto l70
				l71:
					position, tokenIndex = position70, tokenIndex70
					if !_rules[rulestring]() {
						goto l68
					}
				}
			l70:
				if !_rules[rulePAIR_DELIM]() {
					goto l68
				}
				if !_rules[rulevalue]() {
					goto l68
				}
			l72:
				{
					position73, tokenIndex73 := position, tokenIndex
					if !_rules[ruleall_space]() {
						goto l73
					}
					goto l72
				l73:
					position, tokenIndex = position73, tokenIndex73
				}
				add(rulepair, position69)
			}
			return true
		l68:
			position, tokenIndex = position68, tokenIndex68
			return false
		},
		/* 15 value <- <(array / bool_expr / fun_expr / index_expr / math_expr / object / string)> */
		func() bool {
			position74, tokenIndex74 := position, tokenIndex
			{
				position75 := position
				{
					position76, tokenIndex76 := position, tokenIndex
					if !_rules[rulearray]() {
						goto l77
					}
					goto l76
				l77:
					position, tokenIndex = position76, tokenIndex76
					if !_rules[rulebool_expr]() {
						goto l78
					}
					goto l76
				l78:
					position, tokenIndex = position76, tokenIndex76
					if !_rules[rulefun_expr]() {
						goto l79
					}
					goto l76
				l79:
					position, tokenIndex = position76, tokenIndex76
					if !_rules[ruleindex_expr]() {
						goto l80
					}
					goto l76
				l80:
					position, tokenIndex = position76, tokenIndex76
					if !_rules[rulemath_expr]() {
						goto l81
					}
					goto l76
				l81:
					position, tokenIndex = position76, tokenIndex76
					if !_rules[ruleobject]() {
						goto l82
					}
					goto l76
				l82:
					position, tokenIndex = position76, tokenIndex76
					if !_rules[rulestring]() {
						goto l74
					}
				}
			l76:
				add(rulevalue, position75)
			}
			return true
		l74:
			position, tokenIndex = position74, tokenIndex74
			return false
		},
		/* 16 index_expr <- <(ident_chars index_expr_tail+)> */
		func() bool {
			position83, tokenIndex83 := position, tokenIndex
			{
				position84 := position
				if !_rules[ruleident_chars]() {
					goto l83
				}
				if !_rules[ruleindex_expr_tail]() {
					goto l83
				}
			l85:
				{
					position86, tokenIndex86 := position, tokenIndex
					if !_rules[ruleindex_expr_tail]() {
						goto l86
					}
					goto l85
				l86:
					position, tokenIndex = position86, tokenIndex86
				}
				add(ruleindex_expr, position84)
			}
			return true
		l83:
			position, tokenIndex = position83, tokenIndex83
			return false
		},
		/* 17 index_expr_tail <- <((DOT ident_chars) / (INDEX_OPEN sentence INDEX_CLOSE))> */
		func() bool {
			position87, tokenIndex87 := position, tokenIndex
			{
				position88 := position
				{
					position89, tokenIndex89 := position, tokenIndex
					if !_rules[ruleDOT]() {
						goto l90
					}
					if !_rules[ruleident_chars]() {
						goto l90
					}
					goto l89
				l90:
					position, tokenIndex = position89, tokenIndex89
					if !_rules[ruleINDEX_OPEN]() {
						goto l87
					}
					if !_rules[rulesentence]() {
						goto l87
					}
					if !_rules[ruleINDEX_CLOSE]() {
						goto l87
					}
				}
			l89:
				add(ruleindex_expr_tail, position88)
			}
			return true
		l87:
			position, tokenIndex = position87, tokenIndex87
			return false
		},
		/* 18 array <- <(ARRAY_OPEN (value (item_delim value)*)* item_delim ARRAY_CLOSE)> */
		func() bool {
			position91, tokenIndex91 := position, tokenIndex
			{
				position92 := position
				if !_rules[ruleARRAY_OPEN]() {
					goto l91
				}
			l93:
				{
					position94, tokenIndex94 := position, tokenIndex
					if !_rules[rulevalue]() {
						goto l94
					}
				l95:
					{
						position96, tokenIndex96 := position, tokenIndex
						if !_rules[ruleitem_delim]() {
							goto l96
						}
						if !_rules[rulevalue]() {
							goto l96
						}
						goto l95
					l96:
						position, tokenIndex = position96, tokenIndex96
					}
					goto l93
				l94:
					position, tokenIndex = position94, tokenIndex94
				}
				if !_rules[ruleitem_delim]() {
					goto l91
				}
				if !_rules[ruleARRAY_CLOSE]() {
					goto l91
				}
				add(rulearray, position92)
			}
			return true
		l91:
			position, tokenIndex = position91, tokenIndex91
			return false
		},
		/* 19 bool_expr <- <((TRUE / FALSE) all_space*)> */
		func() bool {
			position97, tokenIndex97 := position, tokenIndex
			{
				position98 := position
				{
					position99, tokenIndex99 := position, tokenIndex
					if !_rules[ruleTRUE]() {
						goto l100
					}
					goto l99
				l100:
					position, tokenIndex = position99, tokenIndex99
					if !_rules[ruleFALSE]() {
						goto l97
					}
				}
			l99:
			l101:
				{
					position102, tokenIndex102 := position, tokenIndex
					if !_rules[ruleall_space]() {
						goto l102
					}
					goto l101
				l102:
					position, tokenIndex = position102, tokenIndex102
				}
				add(rulebool_expr, position98)
			}
			return true
		l97:
			position, tokenIndex = position97, tokenIndex97
			return false
		},
		/* 20 item_delim <- <all_space*> */
		func() bool {
			{
				position104 := position
			l105:
				{
					position106, tokenIndex106 := position, tokenIndex
					if !_rules[ruleall_space]() {
						goto l106
					}
					goto l105
				l106:
					position, tokenIndex = position106, tokenIndex106
				}
				add(ruleitem_delim, position104)
			}
			return true
		},
		/* 21 fun_expr <- <(ident GROUP_OPEN (value (item_delim value)*)* item_delim GROUP_CLOSE all_space*)> */
		func() bool {
			position107, tokenIndex107 := position, tokenIndex
			{
				position108 := position
				if !_rules[ruleident]() {
					goto l107
				}
				if !_rules[ruleGROUP_OPEN]() {
					goto l107
				}
			l109:
				{
					position110, tokenIndex110 := position, tokenIndex
					if !_rules[rulevalue]() {
						goto l110
					}
				l111:
					{
						position112, tokenIndex112 := position, tokenIndex
						if !_rules[ruleitem_delim]() {
							goto l112
						}
						if !_rules[rulevalue]() {
							goto l112
						}
						goto l111
					l112:
						position, tokenIndex = position112, tokenIndex112
					}
					goto l109
				l110:
					position, tokenIndex = position110, tokenIndex110
				}
				if !_rules[ruleitem_delim]() {
					goto l107
				}
				if !_rules[ruleGROUP_CLOSE]() {
					goto l107
				}
			l113:
				{
					position114, tokenIndex114 := position, tokenIndex
					if !_rules[ruleall_space]() {
						goto l114
					}
					goto l113
				l114:
					position, tokenIndex = position114, tokenIndex114
				}
				add(rulefun_expr, position108)
			}
			return true
		l107:
			position, tokenIndex = position107, tokenIndex107
			return false
		},
		/* 22 math_expr <- <(number space*)> */
		func() bool {
			position115, tokenIndex115 := position, tokenIndex
			{
				position116 := position
				if !_rules[rulenumber]() {
					goto l115
				}
			l117:
				{
					position118, tokenIndex118 := position, tokenIndex
					if !_rules[rulespace]() {
						goto l118
					}
					goto l117
				l118:
					position, tokenIndex = position118, tokenIndex118
				}
				add(rulemath_expr, position116)
			}
			return true
		l115:
			position, tokenIndex = position115, tokenIndex115
			return false
		},
		/* 23 number <- <(float / int)> */
		func() bool {
			position119, tokenIndex119 := position, tokenIndex
			{
				position120 := position
				{
					position121, tokenIndex121 := position, tokenIndex
					if !_rules[rulefloat]() {
						goto l122
					}
					goto l121
				l122:
					position, tokenIndex = position121, tokenIndex121
					if !_rules[ruleint]() {
						goto l119
					}
				}
			l121:
				add(rulenumber, position120)
			}
			return true
		l119:
			position, tokenIndex = position119, tokenIndex119
			return false
		},
		/* 24 int <- <((MINUS digit+) / digit+)> */
		func() bool {
			position123, tokenIndex123 := position, tokenIndex
			{
				position124 := position
				{
					position125, tokenIndex125 := position, tokenIndex
					if !_rules[ruleMINUS]() {
						goto l126
					}
					if !_rules[ruledigit]() {
						goto l126
					}
				l127:
					{
						position128, tokenIndex128 := position, tokenIndex
						if !_rules[ruledigit]() {
							goto l128
						}
						goto l127
					l128:
						position, tokenIndex = position128, tokenIndex128
					}
					goto l125
				l126:
					position, tokenIndex = position125, tokenIndex125
					if !_rules[ruledigit]() {
						goto l123
					}
				l129:
					{
						position130, tokenIndex130 := position, tokenIndex
						if !_rules[ruledigit]() {
							goto l130
						}
						goto l129
					l130:
						position, tokenIndex = position130, tokenIndex130
					}
				}
			l125:
				add(ruleint, position124)
			}
			return true
		l123:
			position, tokenIndex = position123, tokenIndex123
			return false
		},
		/* 25 float <- <(((MINUS digit+) / digit+) DOT digit+)> */
		func() bool {
			position131, tokenIndex131 := position, tokenIndex
			{
				position132 := position
				{
					position133, tokenIndex133 := position, tokenIndex
					if !_rules[ruleMINUS]() {
						goto l134
					}
					if !_rules[ruledigit]() {
						goto l134
					}
				l135:
					{
						position136, tokenIndex136 := position, tokenIndex
						if !_rules[ruledigit]() {
							goto l136
						}
						goto l135
					l136:
						position, tokenIndex = position136, tokenIndex136
					}
					goto l133
				l134:
					position, tokenIndex = position133, tokenIndex133
					if !_rules[ruledigit]() {
						goto l131
					}
				l137:
					{
						position138, tokenIndex138 := position, tokenIndex
						if !_rules[ruledigit]() {
							goto l138
						}
						goto l137
					l138:
						position, tokenIndex = position138, tokenIndex138
					}
				}
			l133:
				if !_rules[ruleDOT]() {
					goto l131
				}
				if !_rules[ruledigit]() {
					goto l131
				}
			l139:
				{
					position140, tokenIndex140 := position, tokenIndex
					if !_rules[ruledigit]() {
						goto l140
					}
					goto l139
				l140:
					position, tokenIndex = position140, tokenIndex140
				}
				add(rulefloat, position132)
			}
			return true
		l131:
			position, tokenIndex = position131, tokenIndex131
			return false
		},
		/* 26 object <- <(OBJECT_OPEN (pair (item_delim pair)*)* OBJECT_CLOSE)> */
		func() bool {
			position141, tokenIndex141 := position, tokenIndex
			{
				position142 := position
				if !_rules[ruleOBJECT_OPEN]() {
					goto l141
				}
			l143:
				{
					position144, tokenIndex144 := position, tokenIndex
					if !_rules[rulepair]() {
						goto l144
					}
				l145:
					{
						position146, tokenIndex146 := position, tokenIndex
						if !_rules[ruleitem_delim]() {
							goto l146
						}
						if !_rules[rulepair]() {
							goto l146
						}
						goto l145
					l146:
						position, tokenIndex = position146, tokenIndex146
					}
					goto l143
				l144:
					position, tokenIndex = position144, tokenIndex144
				}
				if !_rules[ruleOBJECT_CLOSE]() {
					goto l141
				}
				add(ruleobject, position142)
			}
			return true
		l141:
			position, tokenIndex = position141, tokenIndex141
			return false
		},
		/* 27 string <- <(STRING_DELIM string_body STRING_DELIM space*)> */
		func() bool {
			position147, tokenIndex147 := position, tokenIndex
			{
				position148 := position
				if !_rules[ruleSTRING_DELIM]() {
					goto l147
				}
				if !_rules[rulestring_body]() {
					goto l147
				}
				if !_rules[ruleSTRING_DELIM]() {
					goto l147
				}
			l149:
				{
					position150, tokenIndex150 := position, tokenIndex
					if !_rules[rulespace]() {
						goto l150
					}
					goto l149
				l150:
					position, tokenIndex = position150, tokenIndex150
				}
				add(rulestring, position148)
			}
			return true
		l147:
			position, tokenIndex = position147, tokenIndex147
			return false
		},
		/* 28 string_body <- <(!(STRING_DELIM / newline) .)*> */
		func() bool {
			{
				position152 := position
			l153:
				{
					position154, tokenIndex154 := position, tokenIndex
					{
						position155, tokenIndex155 := position, tokenIndex
						{
							position156, tokenIndex156 := position, tokenIndex
							if !_rules[ruleSTRING_DELIM]() {
								goto l157
							}
							goto l156
						l157:
							position, tokenIndex = position156, tokenIndex156
							if !_rules[rulenewline]() {
								goto l155
							}
						}
					l156:
						goto l154
					l155:
						position, tokenIndex = position155, tokenIndex155
					}
					if !matchDot() {
						goto l154
					}
					goto l153
				l154:
					position, tokenIndex = position154, tokenIndex154
				}
				add(rulestring_body, position152)
			}
			return true
		},
		/* 29 block <- <(simple_block / compound_block)> */
		func() bool {
			position158, tokenIndex158 := position, tokenIndex
			{
				position159 := position
				{
					position160, tokenIndex160 := position, tokenIndex
					if !_rules[rulesimple_block]() {
						goto l161
					}
					goto l160
				l161:
					position, tokenIndex = position160, tokenIndex160
					if !_rules[rulecompound_block]() {
						goto l158
					}
				}
			l160:
				add(ruleblock, position159)
			}
			return true
		l158:
			position, tokenIndex = position158, tokenIndex158
			return false
		},
		/* 30 simple_block <- <(ident block_description OBJECT_OPEN pair+ OBJECT_CLOSE)> */
		func() bool {
			position162, tokenIndex162 := position, tokenIndex
			{
				position163 := position
				if !_rules[ruleident]() {
					goto l162
				}
				if !_rules[ruleblock_description]() {
					goto l162
				}
				if !_rules[ruleOBJECT_OPEN]() {
					goto l162
				}
				if !_rules[rulepair]() {
					goto l162
				}
			l164:
				{
					position165, tokenIndex165 := position, tokenIndex
					if !_rules[rulepair]() {
						goto l165
					}
					goto l164
				l165:
					position, tokenIndex = position165, tokenIndex165
				}
				if !_rules[ruleOBJECT_CLOSE]() {
					goto l162
				}
				add(rulesimple_block, position163)
			}
			return true
		l162:
			position, tokenIndex = position162, tokenIndex162
			return false
		},
		/* 31 block_description <- <(INDEX_OPEN sentence INDEX_CLOSE all_space*)> */
		func() bool {
			position166, tokenIndex166 := position, tokenIndex
			{
				position167 := position
				if !_rules[ruleINDEX_OPEN]() {
					goto l166
				}
				if !_rules[rulesentence]() {
					goto l166
				}
				if !_rules[ruleINDEX_CLOSE]() {
					goto l166
				}
			l168:
				{
					position169, tokenIndex169 := position, tokenIndex
					if !_rules[ruleall_space]() {
						goto l169
					}
					goto l168
				l169:
					position, tokenIndex = position169, tokenIndex169
				}
				add(ruleblock_description, position167)
			}
			return true
		l166:
			position, tokenIndex = position166, tokenIndex166
			return false
		},
		/* 32 compound_block <- <(BLOCK OBJECT_OPEN pair* simple_block+ OBJECT_CLOSE rescue_clause? always_clause?)> */
		func() bool {
			position170, tokenIndex170 := position, tokenIndex
			{
				position171 := position
				if !_rules[ruleBLOCK]() {
					goto l170
				}
				if !_rules[ruleOBJECT_OPEN]() {
					goto l170
				}
			l172:
				{
					position173, tokenIndex173 := position, tokenIndex
					if !_rules[rulepair]() {
						goto l173
					}
					goto l172
				l173:
					position, tokenIndex = position173, tokenIndex173
				}
				if !_rules[rulesimple_block]() {
					goto l170
				}
			l174:
				{
					position175, tokenIndex175 := position, tokenIndex
					if !_rules[rulesimple_block]() {
						goto l175
					}
					goto l174
				l175:
					position, tokenIndex = position175, tokenIndex175
				}
				if !_rules[ruleOBJECT_CLOSE]() {
					goto l170
				}
				{
					position176, tokenIndex176 := position, tokenIndex
					if !_rules[rulerescue_clause]() {
						goto l176
					}
					goto l177
				l176:
					position, tokenIndex = position176, tokenIndex176
				}
			l177:
				{
					position178, tokenIndex178 := position, tokenIndex
					if !_rules[rulealways_clause]() {
						goto l178
					}
					goto l179
				l178:
					position, tokenIndex = position178, tokenIndex178
				}
			l179:
				add(rulecompound_block, position171)
			}
			return true
		l170:
			position, tokenIndex = position170, tokenIndex170
			return false
		},
		/* 33 rescue_clause <- <(RESCUE OBJECT_OPEN simple_block+ OBJECT_CLOSE)> */
		func() bool {
			position180, tokenIndex180 := position, tokenIndex
			{
				position181 := position
				if !_rules[ruleRESCUE]() {
					goto l180
				}
				if !_rules[ruleOBJECT_OPEN]() {
					goto l180
				}
				if !_rules[rulesimple_block]() {
					goto l180
				}
			l182:
				{
					position183, tokenIndex183 := position, tokenIndex
					if !_rules[rulesimple_block]() {
						goto l183
					}
					goto l182
				l183:
					position, tokenIndex = position183, tokenIndex183
				}
				if !_rules[ruleOBJECT_CLOSE]() {
					goto l180
				}
				add(rulerescue_clause, position181)
			}
			return true
		l180:
			position, tokenIndex = position180, tokenIndex180
			return false
		},
		/* 34 always_clause <- <(ALWAYS OBJECT_OPEN simple_block+ OBJECT_CLOSE)> */
		func() bool {
			position184, tokenIndex184 := position, tokenIndex
			{
				position185 := position
				if !_rules[ruleALWAYS]() {
					goto l184
				}
				if !_rules[ruleOBJECT_OPEN]() {
					goto l184
				}
				if !_rules[rulesimple_block]() {
					goto l184
				}
			l186:
				{
					position187, tokenIndex187 := position, tokenIndex
					if !_rules[rulesimple_block]() {
						goto l187
					}
					goto l186
				l187:
					position, tokenIndex = position187, tokenIndex187
				}
				if !_rules[ruleOBJECT_CLOSE]() {
					goto l184
				}
				add(rulealways_clause, position185)
			}
			return true
		l184:
			position, tokenIndex = position184, tokenIndex184
			return false
		},
		/* 35 end <- <!.> */
		func() bool {
			position188, tokenIndex188 := position, tokenIndex
			{
				position189 := position
				{
					position190, tokenIndex190 := position, tokenIndex
					if !matchDot() {
						goto l190
					}
					goto l188
				l190:
					position, tokenIndex = position190, tokenIndex190
				}
				add(ruleend, position189)
			}
			return true
		l188:
			position, tokenIndex = position188, tokenIndex188
			return false
		},
		/* 36 PAIR_DELIM <- <(':' space*)> */
		func() bool {
			position191, tokenIndex191 := position, tokenIndex
			{
				position192 := position
				if buffer[position] != rune(':') {
					goto l191
				}
				position++
			l193:
				{
					position194, tokenIndex194 := position, tokenIndex
					if !_rules[rulespace]() {
						goto l194
					}
					goto l193
				l194:
					position, tokenIndex = position194, tokenIndex194
				}
				add(rulePAIR_DELIM, position192)
			}
			return true
		l191:
			position, tokenIndex = position191, tokenIndex191
			return false
		},
		/* 37 DOT <- <'.'> */
		func() bool {
			position195, tokenIndex195 := position, tokenIndex
			{
				position196 := position
				if buffer[position] != rune('.') {
					goto l195
				}
				position++
				add(ruleDOT, position196)
			}
			return true
		l195:
			position, tokenIndex = position195, tokenIndex195
			return false
		},
		/* 38 STRING_DELIM <- <'\''> */
		func() bool {
			position197, tokenIndex197 := position, tokenIndex
			{
				position198 := position
				if buffer[position] != rune('\'') {
					goto l197
				}
				position++
				add(ruleSTRING_DELIM, position198)
			}
			return true
		l197:
			position, tokenIndex = position197, tokenIndex197
			return false
		},
		/* 39 COMMENT_START <- <'#'> */
		func() bool {
			position199, tokenIndex199 := position, tokenIndex
			{
				position200 := position
				if buffer[position] != rune('#') {
					goto l199
				}
				position++
				add(ruleCOMMENT_START, position200)
			}
			return true
		l199:
			position, tokenIndex = position199, tokenIndex199
			return false
		},
		/* 40 MINUS <- <'-'> */
		func() bool {
			position201, tokenIndex201 := position, tokenIndex
			{
				position202 := position
				if buffer[position] != rune('-') {
					goto l201
				}
				position++
				add(ruleMINUS, position202)
			}
			return true
		l201:
			position, tokenIndex = position201, tokenIndex201
			return false
		},
		/* 41 INDEX_OPEN <- <'['> */
		func() bool {
			position203, tokenIndex203 := position, tokenIndex
			{
				position204 := position
				if buffer[position] != rune('[') {
					goto l203
				}
				position++
				add(ruleINDEX_OPEN, position204)
			}
			return true
		l203:
			position, tokenIndex = position203, tokenIndex203
			return false
		},
		/* 42 INDEX_CLOSE <- <']'> */
		func() bool {
			position205, tokenIndex205 := position, tokenIndex
			{
				position206 := position
				if buffer[position] != rune(']') {
					goto l205
				}
				position++
				add(ruleINDEX_CLOSE, position206)
			}
			return true
		l205:
			position, tokenIndex = position205, tokenIndex205
			return false
		},
		/* 43 ARRAY_OPEN <- <('[' all_space*)> */
		func() bool {
			position207, tokenIndex207 := position, tokenIndex
			{
				position208 := position
				if buffer[position] != rune('[') {
					goto l207
				}
				position++
			l209:
				{
					position210, tokenIndex210 := position, tokenIndex
					if !_rules[ruleall_space]() {
						goto l210
					}
					goto l209
				l210:
					position, tokenIndex = position210, tokenIndex210
				}
				add(ruleARRAY_OPEN, position208)
			}
			return true
		l207:
			position, tokenIndex = position207, tokenIndex207
			return false
		},
		/* 44 ARRAY_CLOSE <- <(']' all_space*)> */
		func() bool {
			position211, tokenIndex211 := position, tokenIndex
			{
				position212 := position
				if buffer[position] != rune(']') {
					goto l211
				}
				position++
			l213:
				{
					position214, tokenIndex214 := position, tokenIndex
					if !_rules[ruleall_space]() {
						goto l214
					}
					goto l213
				l214:
					position, tokenIndex = position214, tokenIndex214
				}
				add(ruleARRAY_CLOSE, position212)
			}
			return true
		l211:
			position, tokenIndex = position211, tokenIndex211
			return false
		},
		/* 45 GROUP_OPEN <- <('(' all_space*)> */
		func() bool {
			position215, tokenIndex215 := position, tokenIndex
			{
				position216 := position
				if buffer[position] != rune('(') {
					goto l215
				}
				position++
			l217:
				{
					position218, tokenIndex218 := position, tokenIndex
					if !_rules[ruleall_space]() {
						goto l218
					}
					goto l217
				l218:
					position, tokenIndex = position218, tokenIndex218
				}
				add(ruleGROUP_OPEN, position216)
			}
			return true
		l215:
			position, tokenIndex = position215, tokenIndex215
			return false
		},
		/* 46 GROUP_CLOSE <- <(')' all_space*)> */
		func() bool {
			position219, tokenIndex219 := position, tokenIndex
			{
				position220 := position
				if buffer[position] != rune(')') {
					goto l219
				}
				position++
			l221:
				{
					position222, tokenIndex222 := position, tokenIndex
					if !_rules[ruleall_space]() {
						goto l222
					}
					goto l221
				l222:
					position, tokenIndex = position222, tokenIndex222
				}
				add(ruleGROUP_CLOSE, position220)
			}
			return true
		l219:
			position, tokenIndex = position219, tokenIndex219
			return false
		},
		/* 47 OBJECT_OPEN <- <('{' all_space*)> */
		func() bool {
			position223, tokenIndex223 := position, tokenIndex
			{
				position224 := position
				if buffer[position] != rune('{') {
					goto l223
				}
				position++
			l225:
				{
					position226, tokenIndex226 := position, tokenIndex
					if !_rules[ruleall_space]() {
						goto l226
					}
					goto l225
				l226:
					position, tokenIndex = position226, tokenIndex226
				}
				add(ruleOBJECT_OPEN, position224)
			}
			return true
		l223:
			position, tokenIndex = position223, tokenIndex223
			return false
		},
		/* 48 OBJECT_CLOSE <- <('}' all_space*)> */
		func() bool {
			position227, tokenIndex227 := position, tokenIndex
			{
				position228 := position
				if buffer[position] != rune('}') {
					goto l227
				}
				position++
			l229:
				{
					position230, tokenIndex230 := position, tokenIndex
					if !_rules[ruleall_space]() {
						goto l230
					}
					goto l229
				l230:
					position, tokenIndex = position230, tokenIndex230
				}
				add(ruleOBJECT_CLOSE, position228)
			}
			return true
		l227:
			position, tokenIndex = position227, tokenIndex227
			return false
		},
		/* 49 BLOCK <- <('b' 'l' 'o' 'c' 'k' !alpha all_space*)> */
		func() bool {
			position231, tokenIndex231 := position, tokenIndex
			{
				position232 := position
				if buffer[position] != rune('b') {
					goto l231
				}
				position++
				if buffer[position] != rune('l') {
					goto l231
				}
				position++
				if buffer[position] != rune('o') {
					goto l231
				}
				position++
				if buffer[position] != rune('c') {
					goto l231
				}
				position++
				if buffer[position] != rune('k') {
					goto l231
				}
				position++
				{
					position233, tokenIndex233 := position, tokenIndex
					if !_rules[rulealpha]() {
						goto l233
					}
					goto l231
				l233:
					position, tokenIndex = position233, tokenIndex233
				}
			l234:
				{
					position235, tokenIndex235 := position, tokenIndex
					if !_rules[ruleall_space]() {
						goto l235
					}
					goto l234
				l235:
					position, tokenIndex = position235, tokenIndex235
				}
				add(ruleBLOCK, position232)
			}
			return true
		l231:
			position, tokenIndex = position231, tokenIndex231
			return false
		},
		/* 50 RESCUE <- <('r' 'e' 's' 'c' 'u' 'e' !alpha all_space*)> */
		func() bool {
			position236, tokenIndex236 := position, tokenIndex
			{
				position237 := position
				if buffer[position] != rune('r') {
					goto l236
				}
				position++
				if buffer[position] != rune('e') {
					goto l236
				}
				position++
				if buffer[position] != rune('s') {
					goto l236
				}
				position++
				if buffer[position] != rune('c') {
					goto l236
				}
				position++
				if buffer[position] != rune('u') {
					goto l236
				}
				position++
				if buffer[position] != rune('e') {
					goto l236
				}
				position++
				{
					position238, tokenIndex238 := position, tokenIndex
					if !_rules[rulealpha]() {
						goto l238
					}
					goto l236
				l238:
					position, tokenIndex = position238, tokenIndex238
				}
			l239:
				{
					position240, tokenIndex240 := position, tokenIndex
					if !_rules[ruleall_space]() {
						goto l240
					}
					goto l239
				l240:
					position, tokenIndex = position240, tokenIndex240
				}
				add(ruleRESCUE, position237)
			}
			return true
		l236:
			position, tokenIndex = position236, tokenIndex236
			return false
		},
		/* 51 ALWAYS <- <('a' 'l' 'w' 'a' 'y' 's' !alpha all_space*)> */
		func() bool {
			position241, tokenIndex241 := position, tokenIndex
			{
				position242 := position
				if buffer[position] != rune('a') {
					goto l241
				}
				position++
				if buffer[position] != rune('l') {
					goto l241
				}
				position++
				if buffer[position] != rune('w') {
					goto l241
				}
				position++
				if buffer[position] != rune('a') {
					goto l241
				}
				position++
				if buffer[position] != rune('y') {
					goto l241
				}
				position++
				if buffer[position] != rune('s') {
					goto l241
				}
				position++
				{
					position243, tokenIndex243 := position, tokenIndex
					if !_rules[rulealpha]() {
						goto l243
					}
					goto l241
				l243:
					position, tokenIndex = position243, tokenIndex243
				}
			l244:
				{
					position245, tokenIndex245 := position, tokenIndex
					if !_rules[ruleall_space]() {
						goto l245
					}
					goto l244
				l245:
					position, tokenIndex = position245, tokenIndex245
				}
				add(ruleALWAYS, position242)
			}
			return true
		l241:
			position, tokenIndex = position241, tokenIndex241
			return false
		},
		/* 52 TRUE <- <('t' 'r' 'u' 'e' !alpha)> */
		func() bool {
			position246, tokenIndex246 := position, tokenIndex
			{
				position247 := position
				if buffer[position] != rune('t') {
					goto l246
				}
				position++
				if buffer[position] != rune('r') {
					goto l246
				}
				position++
				if buffer[position] != rune('u') {
					goto l246
				}
				position++
				if buffer[position] != rune('e') {
					goto l246
				}
				position++
				{
					position248, tokenIndex248 := position, tokenIndex
					if !_rules[rulealpha]() {
						goto l248
					}
					goto l246
				l248:
					position, tokenIndex = position248, tokenIndex248
				}
				add(ruleTRUE, position247)
			}
			return true
		l246:
			position, tokenIndex = position246, tokenIndex246
			return false
		},
		/* 53 FALSE <- <('f' 'a' 'l' 's' 'e' !alpha)> */
		func() bool {
			position249, tokenIndex249 := position, tokenIndex
			{
				position250 := position
				if buffer[position] != rune('f') {
					goto l249
				}
				position++
				if buffer[position] != rune('a') {
					goto l249
				}
				position++
				if buffer[position] != rune('l') {
					goto l249
				}
				position++
				if buffer[position] != rune('s') {
					goto l249
				}
				position++
				if buffer[position] != rune('e') {
					goto l249
				}
				position++
				{
					position251, tokenIndex251 := position, tokenIndex
					if !_rules[rulealpha]() {
						goto l251
					}
					goto l249
				l251:
					position, tokenIndex = position251, tokenIndex251
				}
				add(ruleFALSE, position250)
			}
			return true
		l249:
			position, tokenIndex = position249, tokenIndex249
			return false
		},
		/* 54 EQ <- <('=' '=' all_space*)> */
		nil,
		/* 55 LT <- <('<' all_space*)> */
		nil,
		/* 56 GT <- <('>' all_space*)> */
		nil,
		/* 57 LTE <- <('<' '=' all_space*)> */
		nil,
		/* 58 GTE <- <('>' '=' all_space*)> */
		nil,
		/* 59 AND <- <('&' '&' all_space*)> */
		nil,
		/* 60 OR <- <('|' '|' all_space*)> */
		nil,
	}
	p.rules = _rules
	return nil
}
