// Code generated by unobin. DO NOT EDIT.
package some

import (
	"github.com/cloudboss/unobin/pkg/lang"
	"github.com/cloudboss/unobin/pkg/lang/syntax"
	"github.com/cloudboss/unobin/pkg/runtime"
)

func Library() *runtime.Library {
	return &runtime.Library{
		Name: "some",
		ResourceComposites: map[string]*runtime.CompositeType{
			"foo": {
				Name:       "foo",
				Kind:       runtime.NodeResource,
				SyntaxBody: &syntax.FactoryBody{Description: &lang.StringLit{Value: "a foo"}, Resources: []syntax.NodeDecl{{Kind: syntax.NodeKind("resource"), Name: syntax.Ident{Name: "x"}, Selector: syntax.NodeSelector{Alias: syntax.Ident{Name: "local"}, Export: syntax.Ident{Name: "file"}}, Body: &lang.ObjectLit{Fields: []*lang.Field{{Key: lang.FieldKey{Kind: lang.FieldIdent, Name: "path"}, Value: &lang.StringLit{Value: "/tmp/x"}}, {Key: lang.FieldKey{Kind: lang.FieldIdent, Name: "content"}, Value: &lang.StringLit{Value: "hi"}}, {Key: lang.FieldKey{Kind: lang.FieldIdent, Name: "mode"}, Value: &lang.NumberLit{Value: "420", ParsedInt: 420}}}}}}},
			},
		},
	}
}
