// Code generated by unobin. DO NOT EDIT.
package main

import (
	lib_net "demo-factory/internal/net"
	lib_e2e "example.com/unobin/e2elib"
	"github.com/cloudboss/unobin/pkg/lang"
	"github.com/cloudboss/unobin/pkg/lang/parse"
	"github.com/cloudboss/unobin/pkg/lang/syntax"
	"github.com/cloudboss/unobin/pkg/runner"
	"github.com/cloudboss/unobin/pkg/runtime"
)

var factorySource = parse.NewSourceFile(
	"factory.ub",
	[]int{0, 11, 24, 51, 88, 92, 94},
)

func sp(start, end int) parse.Span {
	return factorySource.Span(start, end)
}

var factoryBody = syntax.FactoryBody{S: sp(9, 93), Imports: []syntax.ImportDecl{{S: sp(28, 0), Alias: syntax.Ident{S: sp(28, 0), Name: "net"}, Ref: &lang.StringLit{S: sp(33, 0), Value: "./libraries/net"}}, {S: sp(55, 0), Alias: syntax.Ident{S: sp(55, 0), Name: "e2e"}, Ref: &lang.StringLit{S: sp(60, 0), Value: "example.com/unobin/e2elib"}}}}

const (
	factoryLibraryPath = ""
	factoryName        = "demo-factory"
)

// Stamped at link time via -ldflags.
var (
	factoryVersion  string
	contentRevision string
	unobinVersion   string
)

func main() {
	runner.Run(runner.Info{
		FactoryName:     factoryName,
		FactoryVersion:  factoryVersion,
		ContentRevision: contentRevision,
		FactoryBody:     &factoryBody,
		LibraryPath:     factoryLibraryPath,
		Libraries: map[string]*runtime.Library{
			"e2e": runtime.LibraryWithPath(
				lib_e2e.Library(),
				"example.com/unobin/e2elib",
			),
			"net": runtime.LibraryWithPath(
				lib_net.Library(),
				"demo-factory/internal/net",
			),
		},
		UnobinVersion: unobinVersion,
	})
}
