// Code generated by unobin. DO NOT EDIT.
package inner

import (
	lib_unobin_library_std "github.com/cloudboss/unobin-library-std"
	"github.com/cloudboss/unobin/pkg/lang"
	"github.com/cloudboss/unobin/pkg/lang/syntax"
	"github.com/cloudboss/unobin/pkg/runtime"
)

func Library() *runtime.Library {
	return &runtime.Library{
		Name: "inner",
		ResourceComposites: map[string]*runtime.CompositeType{
			"hello": {
				Name:       "hello",
				Kind:       runtime.NodeResource,
				SyntaxBody: &syntax.FactoryBody{Description: &lang.StringLit{Value: "inner hello"}, Inputs: []syntax.InputDecl{{Name: syntax.Ident{Name: "path"}, Body: &lang.ObjectLit{Fields: []*lang.Field{{Key: lang.FieldKey{Kind: lang.FieldIdent, Name: "type"}, Value: &lang.TypeAtomic{Name: "string"}}}}, Type: &lang.TypeAtomic{Name: "string"}}}, Imports: []syntax.ImportDecl{{Alias: syntax.Ident{Name: "std"}, Ref: &lang.StringLit{Value: "github.com/cloudboss/unobin-library-std"}}}, Resources: []syntax.NodeDecl{{Kind: syntax.NodeKind("resource"), Name: syntax.Ident{Name: "this"}, Selector: syntax.NodeSelector{Alias: syntax.Ident{Name: "std"}, Export: syntax.Ident{Name: "file"}}, Body: &lang.ObjectLit{Fields: []*lang.Field{{Key: lang.FieldKey{Kind: lang.FieldIdent, Name: "path"}, Value: &lang.DotPath{Root: &lang.Ident{Name: "var"}, Segments: []lang.DotSegment{{Name: "path"}}}}, {Key: lang.FieldKey{Kind: lang.FieldIdent, Name: "content"}, Value: &lang.StringLit{Value: "hi"}}}}}}, Outputs: []syntax.OutputDecl{{Name: syntax.Ident{Name: "path"}, Body: &lang.ObjectLit{Fields: []*lang.Field{{Key: lang.FieldKey{Kind: lang.FieldIdent, Name: "value"}, Value: &lang.DotPath{Root: &lang.Ident{Name: "resource"}, Segments: []lang.DotSegment{{Name: "this"}, {Name: "path"}}}}}}}}},
				Libraries: map[string]*runtime.Library{
					"std": lib_unobin_library_std.Library(),
				},
			},
		},
	}
}
