// Code generated by unobin. DO NOT EDIT.
package main

import (
	lib_outer "demo-factory/internal/outer"
	"github.com/cloudboss/unobin/pkg/runner"
	"github.com/cloudboss/unobin/pkg/runtime"
)

const (
	factoryBody        = "factory: {\n  imports: { outer: 'github.com/example/outer//ub/outer' }\n}\n"
	factoryLibraryPath = ""
	factoryName        = "demo-factory"
)

// Stamped at link time via -ldflags.
var (
	factoryVersion  string
	contentRevision string
	unobinVersion   string
)

func main() {
	runner.Run(runner.Info{
		FactoryName:     factoryName,
		FactoryVersion:  factoryVersion,
		ContentRevision: contentRevision,
		FactoryBody:     factoryBody,
		LibraryPath:     factoryLibraryPath,
		Libraries: map[string]*runtime.Library{
			"outer": runtime.LibraryWithPath(
				lib_outer.Library(),
				"demo-factory/internal/outer",
			),
		},
		UnobinVersion: unobinVersion,
	})
}
