// Code generated by unobin. DO NOT EDIT.
package main

import (
	lib_inner "demo-factory/internal/inner"
	lib_outer "demo-factory/internal/outer"
	lib_unobin_library_std "github.com/cloudboss/unobin-library-std"
	"github.com/cloudboss/unobin/pkg/lang"
	"github.com/cloudboss/unobin/pkg/lang/parse"
	"github.com/cloudboss/unobin/pkg/lang/syntax"
	"github.com/cloudboss/unobin/pkg/runner"
	"github.com/cloudboss/unobin/pkg/runtime"
)

var factorySource = parse.NewSourceFile(
	"factory.ub",
	[]int{0, 11, 70, 72},
)

func sp(start, end int) parse.Span {
	return factorySource.Span(start, end)
}

var factoryBody = syntax.FactoryBody{S: sp(9, 71), Imports: []syntax.ImportDecl{{S: sp(24, 0), Alias: syntax.Ident{S: sp(24, 0), Name: "outer"}, Ref: &lang.StringLit{S: sp(31, 0), Value: "github.com/example/outer//ub/outer"}}}}

const (
	factoryLibraryPath = ""
	factoryName        = "demo-factory"
)

// Stamped at link time via -ldflags.
var (
	factoryVersion  string
	contentRevision string
	unobinVersion   string
)

func main() {
	runner.Run(runner.Info{
		FactoryName:     factoryName,
		FactoryVersion:  factoryVersion,
		ContentRevision: contentRevision,
		FactoryBody:     &factoryBody,
		LibraryPath:     factoryLibraryPath,
		LibraryRegistrations: []runtime.LibraryRegistration{
			{
				LibraryPath: "github.com/cloudboss/unobin-library-std",
				New: func() *runtime.Library {
					library := lib_unobin_library_std.Library()
					return library
				},
			},
			{
				LibraryPath: "github.com/example/inner//ub/inner",
				New: func() *runtime.Library {
					library := lib_inner.Library()
					return library
				},
			},
			{
				LibraryPath: "github.com/example/outer//ub/outer",
				New: func() *runtime.Library {
					library := lib_outer.Library()
					return library
				},
			},
		},
		LibraryBindings: map[string]string{
			"outer": "github.com/example/outer//ub/outer",
		},
		UnobinVersion: unobinVersion,
	})
}
