// Code generated by unobin. DO NOT EDIT.
package outer

import (
	lib_inner "demo-factory/internal/inner"
	"github.com/cloudboss/unobin/pkg/lang"
	"github.com/cloudboss/unobin/pkg/lang/syntax"
	"github.com/cloudboss/unobin/pkg/runtime"
)

func Library() *runtime.Library {
	return &runtime.Library{
		Name: "outer",
		ResourceComposites: map[string]*runtime.CompositeType{
			"greeting": {
				Name:       "greeting",
				Kind:       runtime.NodeResource,
				SyntaxBody: &syntax.FactoryBody{Description: &lang.StringLit{Value: "outer greeting"}, Inputs: []syntax.InputDecl{{Name: syntax.Ident{Name: "path"}, Body: &lang.ObjectLit{Fields: []*lang.Field{{Key: lang.FieldKey{Kind: lang.FieldIdent, Name: "type"}, Value: &lang.TypeAtomic{Name: "string"}}}}, Type: &lang.TypeAtomic{Name: "string"}}}, Imports: []syntax.ImportDecl{{Alias: syntax.Ident{Name: "inner"}, Ref: &lang.StringLit{Value: "github.com/example/inner//ub/inner"}}}, Resources: []syntax.NodeDecl{{Kind: syntax.NodeKind("resource"), Name: syntax.Ident{Name: "x"}, Selector: syntax.NodeSelector{Alias: syntax.Ident{Name: "inner"}, Export: syntax.Ident{Name: "hello"}}, Body: &lang.ObjectLit{Fields: []*lang.Field{{Key: lang.FieldKey{Kind: lang.FieldIdent, Name: "path"}, Value: &lang.DotPath{Root: &lang.Ident{Name: "input"}, Segments: []lang.DotSegment{{Name: "path"}}}}}}}}, Outputs: []syntax.OutputDecl{{Name: syntax.Ident{Name: "path"}, Body: &lang.ObjectLit{Fields: []*lang.Field{{Key: lang.FieldKey{Kind: lang.FieldIdent, Name: "value"}, Value: &lang.DotPath{Root: &lang.Ident{Name: "resource"}, Segments: []lang.DotSegment{{Name: "x"}, {Name: "path"}}}}}}}}},
				Libraries: map[string]*runtime.Library{
					"inner": lib_inner.Library(),
				},
			},
		},
	}
}
