package gogen

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path"
	"path/filepath"
	"slices"
	"strconv"

	"golang.org/x/mod/modfile"

	"github.com/cloudboss/unobin/internal/ownedoutput"
)

const generatedMarker = "// Code generated by unobin. DO NOT EDIT."

func renderOutputFiles(
	name string,
	in Input,
	resources []ResourceSchema,
	dataSources []DataSourceSchema,
	configuration *ConfigurationSchema,
) ([]ownedoutput.File, error) {
	var files []ownedoutput.File
	add := func(path string, content []byte, preserve bool) {
		file := ownedoutput.File{Path: path, Content: content, Mode: 0o644, Preserve: preserve}
		file.RemoveIfUnchanged = preserve && path != "go.mod"
		if !preserve {
			file.Marker = generatedMarker
		}
		files = append(files, file)
	}
	for _, resource := range resources {
		source, err := ResourceFile(resource, in.From)
		if err != nil {
			return nil, fmt.Errorf("render resource %s: %w", resource.GoName, err)
		}
		declarations, implementation, err := splitLifecycleFile(source)
		if err != nil {
			return nil, err
		}
		base := "resources/" + toSnake(resource.GoName)
		add(base+"_rsrc.go", declarations, false)
		add(base+"_impl.go", implementation, true)
	}
	for _, dataSource := range dataSources {
		source, err := DataSourceFile(dataSource, in.From)
		if err != nil {
			return nil, fmt.Errorf("render data source %s: %w", dataSource.GoName, err)
		}
		declarations, implementation, err := splitLifecycleFile(source)
		if err != nil {
			return nil, err
		}
		base := "data/" + toSnake(dataSource.GoName)
		add(base+"_dsrc.go", declarations, false)
		add(base+"_impl.go", implementation, true)
	}
	if configuration != nil && len(configuration.Fields) > 0 {
		source, err := ConfigurationFile(*configuration, name, in.From)
		if err != nil {
			return nil, fmt.Errorf("render configuration.go: %w", err)
		}
		add("configuration.go", source, false)
	}
	library, err := LibraryFile(name, slices.Clone(resources), slices.Clone(dataSources),
		configuration, in.ModulePath, in.From)
	if err != nil {
		return nil, fmt.Errorf("render library.go: %w", err)
	}
	add("library.go", library, false)
	module, err := GoMod(in.ModulePath, in.ReplaceUnobin, in.UnobinVersion)
	if err != nil {
		return nil, err
	}
	parsed, err := modfile.Parse("go.mod", module, nil)
	if err != nil {
		return nil, fmt.Errorf("invalid generated go.mod: %w", err)
	}
	if parsed.Module == nil {
		return nil, fmt.Errorf("generated go.mod is missing its module declaration")
	}
	existing, err := os.ReadFile(filepath.Join(in.OutDir, "go.mod"))
	if err == nil {
		if modfile.ModulePath(existing) != in.ModulePath {
			return nil, fmt.Errorf("existing go.mod declares a different module from %s", in.ModulePath)
		}
	} else if !os.IsNotExist(err) {
		return nil, fmt.Errorf("read existing go.mod: %w", err)
	}
	add("go.mod", module, true)
	return files, nil
}

func splitLifecycleFile(source []byte) ([]byte, []byte, error) {
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, "generated.go", source, parser.ParseComments)
	if err != nil {
		return nil, nil, err
	}
	var declarations, methods []ast.Decl
	for _, declaration := range file.Decls {
		if imports, ok := declaration.(*ast.GenDecl); ok && imports.Tok == token.IMPORT {
			continue
		}
		if method, ok := declaration.(*ast.FuncDecl); ok && method.Recv != nil {
			methods = append(methods, declaration)
		} else {
			declarations = append(declarations, declaration)
		}
	}
	emit := func(declarations []ast.Decl, editable bool) ([]byte, error) {
		used := map[string]bool{}
		for _, declaration := range declarations {
			ast.Inspect(declaration, func(node ast.Node) bool {
				if selector, ok := node.(*ast.SelectorExpr); ok {
					if name, ok := selector.X.(*ast.Ident); ok {
						used[name.Name] = true
					}
				}
				return true
			})
		}
		copy := *file
		copy.Comments, copy.Decls, copy.Imports = nil, nil, nil
		imports := &ast.GenDecl{Tok: token.IMPORT, Lparen: token.Pos(1)}
		for _, spec := range file.Imports {
			importPath, err := strconv.Unquote(spec.Path.Value)
			if err != nil {
				return nil, err
			}
			name := path.Base(importPath)
			if spec.Name != nil {
				name = spec.Name.Name
			}
			if used[name] {
				imports.Specs = append(imports.Specs, spec)
			}
		}
		if len(imports.Specs) > 0 {
			copy.Decls = append(copy.Decls, imports)
		}
		copy.Decls = append(copy.Decls, declarations...)
		for _, comment := range ast.NewCommentMap(fset, file, file.Comments).Filter(&copy).Comments() {
			if comment.Pos() > file.Package {
				copy.Comments = append(copy.Comments, comment)
			}
		}
		copy.Doc = nil
		var out bytes.Buffer
		if editable {
			out.WriteString("// Lifecycle implementations. Edit this file to implement the provider.\n\n")
		} else {
			for _, group := range file.Comments {
				if group.End() >= file.Package {
					break
				}
				for _, comment := range group.List {
					out.WriteString(comment.Text + "\n")
				}
			}
			out.WriteString("\n")
		}
		if err := format.Node(&out, fset, &copy); err != nil {
			return nil, err
		}
		return format.Source(out.Bytes())
	}
	declSource, err := emit(declarations, false)
	if err != nil {
		return nil, nil, err
	}
	implSource, err := emit(methods, true)
	return declSource, implSource, err
}
