package gogen

import (
	"go/parser"
	"go/token"
	"strings"
	"testing"
)

func sampleResourceSchema() ResourceSchema {
	return ResourceSchema{
		GoName:      "S3Bucket",
		CloudType:   "AWS::S3::Bucket",
		Description: "An S3 bucket for storing objects",
		InputFields: []Field{
			{Name: "BucketName", GoType: "string", Description: "The bucket name", Required: true},
			{Name: "Tags", GoType: "map[string]string", Description: "Resource tags", Required: false},
		},
		OutputFields: []Field{
			{Name: "Arn", GoType: "string", Description: "The ARN of the bucket"},
			{Name: "DomainName", GoType: "string", Description: "The domain name"},
		},
		CreateOnlyFields:  []string{"BucketName"},
		PrimaryIdentifier: []string{"BucketName"},
	}
}

func TestResourceFileProducesParseableGo(t *testing.T) {
	src, err := ResourceFile(sampleResourceSchema(), "tf")
	if err != nil {
		t.Fatalf("ResourceFile: %v", err)
	}

	fset := token.NewFileSet()
	_, err = parser.ParseFile(fset, "s3_bucket.go", src, parser.AllErrors)
	if err != nil {
		t.Fatalf("generated source does not parse: %v\n\nSource:\n%s", err, src)
	}

	s := string(src)
	checks := []string{
		"Generated by unobin generate gomodule --from tf",
		"package resources",
		"type S3Bucket struct {",
		"type S3BucketOutput struct {",
		"BucketName string `mapstructure:\"bucket-name\"`",
		"Tags map[string]string `mapstructure:\"tags\"`",
		"Arn string `mapstructure:\"arn\"`",
		"func (r *S3Bucket) Create(ctx context.Context, cfg any) (any, error)",
		"func (r *S3Bucket) Read(ctx context.Context, cfg any, priorOutputs any) (any, error)",
		"func (r *S3Bucket) Update(ctx context.Context, cfg any, priorOutputs any) (any, error)",
		"func (r *S3Bucket) Delete(ctx context.Context, cfg any, priorOutputs any) error",
		"return []string{\n\t\t\"bucket-name\",\n\t}",
		`panic("not implemented")`,
	}
	for _, c := range checks {
		if !strings.Contains(s, c) {
			t.Errorf("expected generated source to contain %q", c)
		}
	}
}

func TestResourceFileNoCreateOnlyFields(t *testing.T) {
	rs := sampleResourceSchema()
	rs.CreateOnlyFields = nil

	src, err := ResourceFile(rs, "tf")
	if err != nil {
		t.Fatalf("ResourceFile: %v", err)
	}

	fset := token.NewFileSet()
	_, err = parser.ParseFile(fset, "s3_bucket.go", src, parser.AllErrors)
	if err != nil {
		t.Fatalf("generated source does not parse: %v", err)
	}

	s := string(src)
	if strings.Contains(s, "return []string{") {
		t.Error("expected no create-only return when CreateOnlyFields is nil")
	}
}

func TestResourceFileNoFields(t *testing.T) {
	rs := ResourceSchema{
		GoName:    "Empty",
		CloudType: "AWS::Empty::Resource",
	}
	src, err := ResourceFile(rs, "tf")
	if err != nil {
		t.Fatalf("ResourceFile: %v", err)
	}
	fset := token.NewFileSet()
	_, err = parser.ParseFile(fset, "empty.go", src, parser.AllErrors)
	if err != nil {
		t.Fatalf("generated source does not parse: %v", err)
	}
}

func TestDataSourceFileProducesParseableGo(t *testing.T) {
	ds := DataSourceSchema{
		GoName:      "AMI",
		CloudType:   "AWS::EC2::AMI",
		Description: "An EC2 AMI",
		InputFields: []Field{
			{Name: "ImageId", GoType: "string", Description: "The image ID", Required: true},
		},
		OutputFields: []Field{
			{Name: "Architecture", GoType: "string", Description: "The CPU architecture"},
		},
	}

	src, err := DataSourceFile(ds, "tf")
	if err != nil {
		t.Fatalf("DataSourceFile: %v", err)
	}

	fset := token.NewFileSet()
	_, err = parser.ParseFile(fset, "ami.go", src, parser.AllErrors)
	if err != nil {
		t.Fatalf("generated source does not parse: %v\n\nSource:\n%s", err, src)
	}

	s := string(src)
	if !strings.Contains(s, "package data") {
		t.Error("expected package data")
	}
	if !strings.Contains(s, "func (d *AMI) Read(ctx context.Context, cfg any) (any, error)") {
		t.Error("expected Read method on data source")
	}
}

func TestModuleFileProducesParseableGo(t *testing.T) {
	resources := []ResourceSchema{sampleResourceSchema()}

	src, err := ModuleFile("aws", resources, nil, "example.com/aws", "tf")
	if err != nil {
		t.Fatalf("ModuleFile: %v", err)
	}

	fset := token.NewFileSet()
	_, err = parser.ParseFile(fset, "module.go", src, parser.AllErrors)
	if err != nil {
		t.Fatalf("generated source does not parse: %v\n\nSource:\n%s", err, src)
	}

	s := string(src)
	checks := []string{
		"Generated by unobin generate gomodule --from tf",
		"package aws",
		`"example.com/aws/resources"`,
		"func Module() *runtime.Module",
		"Resources: map[string]runtime.ResourceType",
		`"s3-bucket": {`,
		`New:           func() runtime.Resource { return &resources.S3Bucket{} }`,
	}
	for _, c := range checks {
		if !strings.Contains(s, c) {
			t.Errorf("expected generated source to contain %q", c)
		}
	}
	if strings.Contains(s, "DataSources") {
		t.Error("expected no DataSources section")
	}
	if strings.Contains(s, "/data") {
		t.Error("expected no /data import when no data sources")
	}
}

func TestModuleFileWithDataSources(t *testing.T) {
	dataSources := []DataSourceSchema{
		{GoName: "AMI", CloudType: "AWS::EC2::AMI", Description: "An AMI"},
	}

	src, err := ModuleFile("aws", nil, dataSources, "example.com/aws", "tf")
	if err != nil {
		t.Fatalf("ModuleFile: %v", err)
	}

	fset := token.NewFileSet()
	_, err = parser.ParseFile(fset, "module.go", src, parser.AllErrors)
	if err != nil {
		t.Fatalf("generated source does not parse: %v\n\nSource:\n%s", err, src)
	}

	s := string(src)
	if !strings.Contains(s, `"example.com/aws/data"`) {
		t.Error("expected /data import")
	}
	if !strings.Contains(s, `New:         func() runtime.DataSource { return &data.AMI{} }`) {
		t.Error("expected qualified data source type reference")
	}
	if strings.Contains(s, "Resources") {
		t.Error("expected no Resources section when none provided")
	}
}

func TestGoMod(t *testing.T) {
	src, err := GoMod("example.com/modules/testmod", "")
	if err != nil {
		t.Fatalf("GoMod: %v", err)
	}

	s := string(src)
	checks := []string{
		"module example.com/modules/testmod",
		"go 1.26",
		"github.com/cloudboss/unobin",
	}
	for _, c := range checks {
		if !strings.Contains(s, c) {
			t.Errorf("expected go.mod to contain %q", c)
		}
	}
	if strings.Contains(s, "replace") {
		t.Error("expected no replace directive when replaceUnobin is empty")
	}
}

func TestGoModWithReplace(t *testing.T) {
	src, err := GoMod("example.com/modules/testmod", "/home/user/unobin")
	if err != nil {
		t.Fatalf("GoMod: %v", err)
	}

	s := string(src)
	if !strings.Contains(s, "replace github.com/cloudboss/unobin => /home/user/unobin") {
		t.Errorf("expected replace directive, got:\n%s", s)
	}
}
