// Code generated by unobin. DO NOT EDIT.
package files

import (
	lib_e2elib "example.com/unobin/e2elib"
	"github.com/cloudboss/unobin/pkg/lang"
	"github.com/cloudboss/unobin/pkg/lang/syntax"
	"github.com/cloudboss/unobin/pkg/runtime"
)

func Library() *runtime.Library {
	e2elibLib := lib_e2elib.Library()
	e2elibLib.Constraints = map[string][]lang.ConstraintSpec{
		"resource.file": {
			{Kind: "predicate", When: "true", Require: "((input.path != null) && (@core.length(input.path) >= 1))", Message: "path is required"},
			{Kind: "predicate", When: "true", Require: "(input.mode == null || input.mode >= 0)", Message: "mode must be non-negative"},
		},
	}
	e2elibLib.Defaults = map[string][]lang.DefaultSpec{
		"resource.file": {
			{Field: "input.mode", Value: "420"},
			{Field: "input.create-parents", Value: "true"},
			{Field: "input.tags", Optional: true},
		},
	}
	return &runtime.Library{
		Name: "files",
		ResourceComposites: map[string]*runtime.CompositeType{
			"archive": {
				Name:       "archive",
				Kind:       runtime.NodeResource,
				SyntaxBody: &syntax.FactoryBody{Inputs: []syntax.InputDecl{{Name: syntax.Ident{Name: "path"}, Body: &lang.ObjectLit{Fields: []*lang.Field{{Key: lang.FieldKey{Kind: lang.FieldIdent, Name: "type"}, Value: &lang.TypeAtomic{Name: "string"}}}}, Type: &lang.TypeAtomic{Name: "string"}}, {Name: syntax.Ident{Name: "body"}, Body: &lang.ObjectLit{Fields: []*lang.Field{{Key: lang.FieldKey{Kind: lang.FieldIdent, Name: "type"}, Value: &lang.TypeAtomic{Name: "string"}}}}, Type: &lang.TypeAtomic{Name: "string"}}, {Name: syntax.Ident{Name: "e2e-config"}, Body: &lang.ObjectLit{Fields: []*lang.Field{{Key: lang.FieldKey{Kind: lang.FieldIdent, Name: "type"}, Value: &lang.TypeLibraryConfig{Path: &lang.StringLit{Value: "example.com/unobin/e2elib"}}}}}, Type: &lang.TypeLibraryConfig{Path: &lang.StringLit{Value: "example.com/unobin/e2elib"}}}}, Imports: []syntax.ImportDecl{{Alias: syntax.Ident{Name: "e2e"}, Ref: &lang.StringLit{Value: "example.com/unobin/e2elib"}}}, LibraryConfigs: []syntax.LibraryConfigDecl{{Alias: syntax.Ident{Name: "e2e"}, Value: &lang.DotPath{Root: &lang.Ident{Name: "input"}, Segments: []lang.DotSegment{{Name: "e2e-config"}}}}}, Resources: []syntax.NodeDecl{{Kind: syntax.NodeKind("resource"), Name: syntax.Ident{Name: "member"}, Selector: syntax.NodeSelector{Alias: syntax.Ident{Name: "e2e"}, Export: syntax.Ident{Name: "file"}}, Body: &lang.ObjectLit{Fields: []*lang.Field{{Key: lang.FieldKey{Kind: lang.FieldIdent, Name: "path"}, Value: &lang.DotPath{Root: &lang.Ident{Name: "input"}, Segments: []lang.DotSegment{{Name: "path"}}}}, {Key: lang.FieldKey{Kind: lang.FieldIdent, Name: "content"}, Value: &lang.DotPath{Root: &lang.Ident{Name: "input"}, Segments: []lang.DotSegment{{Name: "body"}}}}}}}}},
				Libraries: map[string]*runtime.Library{
					"e2e": e2elibLib,
				},
			},
		},
	}
}
