// Code generated by unobin. DO NOT EDIT.
package main

import (
	lib_lib "example.com/lib/v2"
	"github.com/cloudboss/unobin/pkg/lang"
	"github.com/cloudboss/unobin/pkg/lang/parse"
	"github.com/cloudboss/unobin/pkg/lang/syntax"
	"github.com/cloudboss/unobin/pkg/runner"
	"github.com/cloudboss/unobin/pkg/runtime"
)

var factorySource = parse.NewSourceFile(
	"factory.ub",
	[]int{0, 11, 52, 54},
)

func sp(start, end int) parse.Span {
	return factorySource.Span(start, end)
}

var factoryBody = syntax.FactoryBody{S: sp(9, 53), Imports: []syntax.ImportDecl{{S: sp(24, 0), Alias: syntax.Ident{S: sp(24, 0), Name: "lib"}, Ref: &lang.StringLit{S: sp(29, 0), Value: "example.com/lib/v2"}}}}

const (
	factoryLibraryPath = ""
	factoryName        = "demo-factory"
)

// Stamped at link time via -ldflags.
var (
	factoryVersion  string
	contentRevision string
	unobinVersion   string
)

func main() {
	runner.Run(runner.Info{
		FactoryName:     factoryName,
		FactoryVersion:  factoryVersion,
		ContentRevision: contentRevision,
		FactoryBody:     &factoryBody,
		LibraryPath:     factoryLibraryPath,
		Libraries: map[string]*runtime.Library{
			"lib": runtime.LibraryWithPath(
				lib_lib.Library(),
				"example.com/lib/v2",
			),
		},
		UnobinVersion: unobinVersion,
	})
}
